// src/lib/prompts/hyperrealism-text/atmosfera.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Atmosfera";
const CATEGORY = "Ambiente";

export const hyperrealismTextPromptsAtmosfera = [
{ id: "hyper-atm-ambiente-001", title: "Aria pulita", summary: "Non ci credo.", area: AREA, category: CATEGORY, prompt: "aria pulita, alta visibilità, neutrale atmosfera realistica" },
{ id: "hyper-atm-ambiente-002", title: "Rendere morbido", summary: "Profondità.", area: AREA, category: CATEGORY, prompt: "morbido e naturale, realistica profondità atmosferica" },
{ id: "hyper-atm-ambiente-003", title: "Fogella leggera", summary: "Subtle.", area: AREA, category: CATEGORY, prompt: "nebbia leggera, non copre il soggetto, realistico" },
{ id: "hyper-atm-ambiente-004", title: "Fossa densa", summary: "Controllo drammatico.", area: AREA, category: CATEGORY, prompt: "nebbia densa realistica, bordi morbidi, nessun look CGI" },
{ id: "hyper-atm-ambiente-005", title: "Nebbia urbana", summary: "Una vera città.", area: AREA, category: CATEGORY, prompt: "nebbia urbana morbida, lanterne diffuse, realismo fotografico" },
{ id: "hyper-atm-ambiente-006", title: "Polvere nell'aria", summary: "Le particelle sottili.", area: AREA, category: CATEGORY, prompt: "polvere sottile nell'aria, particelle sottili visibili contro la luce" },
{ id: "hyper-atm-ambiente-007", title: "Particelle in contraluz", summary: "Cinematica.", area: AREA, category: CATEGORY, prompt: "particelle visibili nel contralux, dispersione naturale" },
{ id: "hyper-atm-ambiente-008", title: "Fumo delicato", summary: "Atmosfera morbida.", area: AREA, category: CATEGORY, prompt: "fumo mite realistico, nessuna saturazione rara, dispersione naturale" },
{ id: "hyper-atm-ambiente-009", title: "Fumo di cucina", summary: "Vapore vero.", area: AREA, category: CATEGORY, prompt: "fumo realistico / cucina, umidità visibile, senza plastica" },
{ id: "hyper-atm-ambiente-010", title: "Vapore sottile", summary: "Davvero caldo.", area: AREA, category: CATEGORY, prompt: "vapore sottile, condensazione mite, realismo fotografico" },

{ id: "hyper-atm-ambiente-011", title: "Pioggia di pinna", summary: "Piccole gocce.", area: AREA, category: CATEGORY, prompt: "pioggia fine realistica, piccole gocce, ambiente umido" },
{ id: "hyper-atm-ambiente-012", title: "Pioggia intensa", summary: "Storm.", area: AREA, category: CATEGORY, prompt: "pioggia intensa, realistica, spatter coerente, minore visibilità" },
{ id: "hyper-atm-ambiente-013", title: "(sottotitolo)", summary: "Un vero POV.", area: AREA, category: CATEGORY, prompt: "gocce sottili sulla lente, effetto inesagerato, effettivo" },
{ id: "hyper-atm-ambiente-014", title: "Stagni riflettenti", summary: "Riflessioni reali.", area: AREA, category: CATEGORY, prompt: "piscine con riflessi coerenti, distorsione naturale dell'acqua" },
{ id: "hyper-atm-ambiente-015", title: "Asfalto bagnato", summary: "Un vero splendore.", area: AREA, category: CATEGORY, prompt: "asfalto umido realistico, speculazione naturale, nessun falso neon" },
{ id: "hyper-atm-ambiente-016", title: "Alta umidità", summary: "Aria pesante.", area: AREA, category: CATEGORY, prompt: "elevata umidità, nebbia leggera, pelle e superfici con lucentezza naturale" },
{ id: "hyper-atm-ambiente-017", title: "Condensazione in vetro", summary: "Dettaglio.", area: AREA, category: CATEGORY, prompt: "condensazione in vetro, gocce e fusibile realistico" },
{ id: "hyper-atm-ambiente-018", title: "A volontà fredda", summary: "Respirazione visibile.", area: AREA, category: CATEGORY, prompt: "respiro vaho in clima freddo, realistico e sottile" },
{ id: "hyper-atm-ambiente-019", title: "Nevina leggera", summary: "Bei sacchi.", area: AREA, category: CATEGORY, prompt: "neve leggera, fiocchi sottili, accumulo minimo realistico" },
{ id: "hyper-atm-ambiente-020", title: "Intenso neve", summary: "Bassa visibilità.", area: AREA, category: CATEGORY, prompt: "neve intensa e realistica, visibilità ridotta, nessun look 3D" },

{ id: "hyper-atm-ambiente-021", title: "Dawn", summary: "Capelli molli.", area: AREA, category: CATEGORY, prompt: "atmosfera di alba, nebbia morbida, toni naturali" },
{ id: "hyper-atm-ambiente-022", title: "Tempo d'oro", summary: "Molto caldo.", area: AREA, category: CATEGORY, prompt: "realistica ora d'oro, luce calda morbida, ombre lunghe" },
{ id: "hyper-atm-ambiente-023", title: "Mezza giornata", summary: "Molto duro.", area: AREA, category: CATEGORY, prompt: "luce di mezzogiorno, ombre marcate, contrasto realistico" },
{ id: "hyper-atm-ambiente-024", title: "Sole", summary: "Un vero cielo.", area: AREA, category: CATEGORY, prompt: "tramonto realistico, cielo con gradiente naturale, senza HDR" },
{ id: "hyper-atm-ambiente-025", title: "Tempo blu", summary: "Blu morbido.", area: AREA, category: CATEGORY, prompt: "tempo blu realistico, ambiente freddo morbido, luci calde nel tempo" },
{ id: "hyper-atm-ambiente-026", title: "Notte (senza neon)", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "notte realistica, scarsa luce ambientale, nessun neon esagerato" },
{ id: "hyper-atm-ambiente-027", title: "Notte con lanterne", summary: "Disseminazione.", area: AREA, category: CATEGORY, prompt: "fari con diffusione liscia, fioritura minima realistica" },
{ id: "hyper-atm-ambiente-028", title: "Interno notturno", summary: "Basso calore leggero.", area: AREA, category: CATEGORY, prompt: "interno notturno, luce calda reale, ombre morbide, nessun rumore artificiale" },
{ id: "hyper-atm-ambiente-029", title: "Giorno nuvoloso", summary: "Fuse.", area: AREA, category: CATEGORY, prompt: "giorno nuvoloso, luce diffusa, leggermente off colori realistici" },
{ id: "hyper-atm-ambiente-030", title: "Clima della tempesta", summary: "BP.", area: AREA, category: CATEGORY, prompt: "realistico cielo tempestoso, contrasto drammatico controllato" },

{ id: "hyper-atm-ambiente-031", title: "Vento moderato", summary: "Movimento sottile.", area: AREA, category: CATEGORY, prompt: "vento leggero: capelli / tessuto con movimento sottile e realistico" },
{ id: "hyper-atm-ambiente-032", title: "Vento forte", summary: "Azione.", area: AREA, category: CATEGORY, prompt: "vento forte realistico: vestiti / capelli coerenti, nessuna deformazione" },
{ id: "hyper-atm-ambiente-033", title: "La sabbia nell'aria", summary: "Deserto.", area: AREA, category: CATEGORY, prompt: "sabbia sospesa realistica, grani fini, visibilità ridotta" },
{ id: "hyper-atm-ambiente-034", title: "Dune", summary: "Texture.", area: AREA, category: CATEGORY, prompt: "polvere che sorge in dune, texture realistica, senza modelli ripetuti" },
{ id: "hyper-atm-ambiente-035", title: "Brezza tesa", summary: "Vattene.", area: AREA, category: CATEGORY, prompt: "brezza marina, nebbia salina leggera, ambiente umido" },
{ id: "hyper-atm-ambiente-036", title: "Spray di onde", summary: "Tette.", area: AREA, category: CATEGORY, prompt: "spray ondulato realistico, gocce sottili nell'aria, luce costante" },
{ id: "hyper-atm-ambiente-037", title: "Ghiaccio e gelo", summary: "Davvero freddo.", area: AREA, category: CATEGORY, prompt: "gelo sottile su superfici, cristalli realistici, non CGI" },
{ id: "hyper-atm-ambiente-038", title: "Llovizna + nebline", summary: "Mood.", area: AREA, category: CATEGORY, prompt: "pioggia con nebbia, atmosfera morbida, contrasto controllato" },
{ id: "hyper-atm-ambiente-039", title: "Haze di calore", summary: "Onde.", area: AREA, category: CATEGORY, prompt: "calore rendere sottile (onda di calore), effetto realistico morbido" },
{ id: "hyper-atm-ambiente-040", title: "Ambiente asciutto", summary: "Polvere minima.", area: AREA, category: CATEGORY, prompt: "ambiente asciutto, polvere minima su superfici, realistico" },

{ id: "hyper-atm-ambiente-041", title: "Bokeh leggero", summary: "Notte.", area: AREA, category: CATEGORY, prompt: "bokeh di luci realistiche in background, forma naturale, senza modelli" },
{ id: "hyper-atm-ambiente-042", title: "Fiore minimo", summary: "Nessun falso.", area: AREA, category: CATEGORY, prompt: "fioritura minima e realistica, nessun bagliore esagerato" },
{ id: "hyper-atm-ambiente-043", title: "Lare realistico", summary: "Molto sottile.", area: AREA, category: CATEGORY, prompt: "lente flare realistico molto sottile, nessun gioco di stile video" },
{ id: "hyper-atm-ambiente-044", title: "Riflessioni bagnate", summary: "Dettagli.", area: AREA, category: CATEGORY, prompt: "riflessi umidi naturali su superfici, speculari coerenti" },
{ id: "hyper-atm-ambiente-045", title: "Motite dell'aria interna", summary: "Casa / luce.", area: AREA, category: CATEGORY, prompt: "polvere visibile motites in raggio di luce interna, realistico" },
{ id: "hyper-atm-ambiente-046", title: "Raggi di luce", summary: "Davvero volumetrico.", area: AREA, category: CATEGORY, prompt: "raggi di luce volumetrica realistici, densità morbida" },
{ id: "hyper-atm-ambiente-047", title: "Volumetrico morbido", summary: "Cinema.", area: AREA, category: CATEGORY, prompt: "morbido volumetrico, senza nebbia eccessiva, realismo" },
{ id: "hyper-atm-ambiente-048", title: "Atmosfera di studio", summary: "Pulito.", area: AREA, category: CATEGORY, prompt: "ambiente di studio pulito, nessuna particelle, sguardo commerciale" },
{ id: "hyper-atm-ambiente-049", title: "Atmosfera dietro le quinte", summary: "Calore.", area: AREA, category: CATEGORY, prompt: "backstage realistico: luce pratica, aria leggermente carica" },
{ id: "hyper-atm-ambiente-050", title: "Atmosfera di strada", summary: "Vero.", area: AREA, category: CATEGORY, prompt: "atmosfera di strada realistica, inquinamento luminoso / labirinto naturale" },

{ id: "hyper-atm-ambiente-051", title: "Umidità della pelle", summary: "Un vero splendore.", area: AREA, category: CATEGORY, prompt: "lucentezza di umidità in pelle realistica, senza plastica" },
{ id: "hyper-atm-ambiente-052", title: "Rocío", summary: "Piccole gocce.", area: AREA, category: CATEGORY, prompt: "rugiada su foglie / superfici, piccole gocce, macro realistico" },
{ id: "hyper-atm-ambiente-053", title: "Micro gocce", summary: "Dettaglio.", area: AREA, category: CATEGORY, prompt: "disperse micro gocce, tensione superficiale realistica" },
{ id: "hyper-atm-ambiente-054", title: "Superficie del terreno", summary: "Speculare.", area: AREA, category: CATEGORY, prompt: "superficie umida realistica, riflessione controllata, texture visibile" },
{ id: "hyper-atm-ambiente-055", title: "Vetro bagnato", summary: "Interno freddo.", area: AREA, category: CATEGORY, prompt: "vetro tinto realistico, condensazione naturale" },
{ id: "hyper-atm-ambiente-056", title: "Respirazione visibile", summary: "Tempo freddo.", area: AREA, category: CATEGORY, prompt: "respirazione visibile sottile, clima freddo e realistico" },
{ id: "hyper-atm-ambiente-057", title: "Cenere", summary: "Niente apocalisse.", area: AREA, category: CATEGORY, prompt: "cenere leggera nell'aria, particelle fini e realistiche" },
{ id: "hyper-atm-ambiente-058", title: "Spa di luce", summary: "Workshop.", area: AREA, category: CATEGORY, prompt: "luce laboratorio scintille, esposizione realistica, nessun fuochi d'artificio" },
{ id: "hyper-atm-ambiente-059", title: "Fumo industriale", summary: "Morbido.", area: AREA, category: CATEGORY, prompt: "fumo industriale morbido e credibile, senza densità impossibile" },
{ id: "hyper-atm-ambiente-060", title: "Barriera alimentare", summary: "Appetite.", area: AREA, category: CATEGORY, prompt: "vaho sottile che esce dal cibo, realistico, non esagerato" },

{ id: "hyper-atm-ambiente-061", title: "Bokeh Natale (reale)", summary: "Sembri caldo.", area: AREA, category: CATEGORY, prompt: "bokeh di luci calde realistiche, senza forme ripetute" },
{ id: "hyper-atm-ambiente-062", title: "Festival (naturale)", summary: "Sei morbida.", area: AREA, category: CATEGORY, prompt: "luci di festival realistiche, esposizione corretta, nessun coltello neon" },
{ id: "hyper-atm-ambiente-063", title: "Lampada pratica", summary: "Interno.", area: AREA, category: CATEGORY, prompt: "luce pratica (lamp) scena illuminante, ombre coerenti" },
{ id: "hyper-atm-ambiente-064", title: "Finestra Fuse", summary: "Luce morbida.", area: AREA, category: CATEGORY, prompt: "luce diffusa della finestra, ambiente naturale, contrasto morbido" },
{ id: "hyper-atm-ambiente-065", title: "Sole", summary: "Tenda.", area: AREA, category: CATEGORY, prompt: "raggio di sole che entra, polvere sottile, aspetto realistico" },
{ id: "hyper-atm-ambiente-066", title: "Ombre ciondola", summary: "Interno.", area: AREA, category: CATEGORY, prompt: "tende realistiche, modello morbido, non perfetto" },
{ id: "hyper-atm-ambiente-067", title: "Riflesso dell'acqua", summary: "Piscina.", area: AREA, category: CATEGORY, prompt: "riflesso proiettato, morbido e realistico dell'acqua" },
{ id: "hyper-atm-ambiente-068", title: "Morbido caustico", summary: "Acqua vera.", area: AREA, category: CATEGORY, prompt: "realistico morbido (acqua) caustico, senza motivo artificiale" },
{ id: "hyper-atm-ambiente-069", title: "Ambiente forestale", summary: "Fumo.", area: AREA, category: CATEGORY, prompt: "foresta umida con nebbia leggera, colori naturali" },
{ id: "hyper-atm-ambiente-070", title: "Montagna fredda", summary: "Va bene.", area: AREA, category: CATEGORY, prompt: "aria di montagna fredda, nitidezza naturale, nebbia minima" },

{ id: "hyper-atm-ambiente-071", title: "Città dopo la pioggia", summary: "Riflessioni.", area: AREA, category: CATEGORY, prompt: "città dopo la pioggia, riflessi asfaltati, realistici" },
{ id: "hyper-atm-ambiente-072", title: "Wet road", summary: "Notte.", area: AREA, category: CATEGORY, prompt: "strada bagnata, riflessi di fari reali, senza neon esagerato" },
{ id: "hyper-atm-ambiente-073", title: "Interno con fumo leggero", summary: "Cinema.", area: AREA, category: CATEGORY, prompt: "interno con raggio molto leggero, raggi morbidi e realistici" },
{ id: "hyper-atm-ambiente-074", title: "Workshop con polvere", summary: "Industriale.", area: AREA, category: CATEGORY, prompt: "laboratorio con polvere d'aria, luce laterale, texture reale" },
{ id: "hyper-atm-ambiente-075", title: "Cucina con vapore", summary: "Cibo.", area: AREA, category: CATEGORY, prompt: "cucina con vapore piatto, umidità realistica" },
{ id: "hyper-atm-ambiente-076", title: "Caffetteria a vapore", summary: "Caffe'.", area: AREA, category: CATEGORY, prompt: "vapore caffè realistico, atmosfera calda, nessun eccesso" },
{ id: "hyper-atm-ambiente-077", title: "Vaho nella finestra", summary: "Inverno.", area: AREA, category: CATEGORY, prompt: "vaho nella finestra interna, condensazione naturale, dettaglio reale" },
{ id: "hyper-atm-ambiente-078", title: "Via della nebbia", summary: "Mood.", area: AREA, category: CATEGORY, prompt: "nebbia in strada, fari diffusi, profondità realistica" },
{ id: "hyper-atm-ambiente-079", title: "Pioggia con contraluz", summary: "Tette.", area: AREA, category: CATEGORY, prompt: "pioggia con contraluz, gocce visibili, esposizione realistica" },
{ id: "hyper-atm-ambiente-080", title: "Neve con contraluz", summary: "Tazze.", area: AREA, category: CATEGORY, prompt: "neve con contraluz, fiocchi visibili, vero ambiente freddo" },

{ id: "hyper-atm-ambiente-081", title: "Ambiente minimo", summary: "Niente distrazioni.", area: AREA, category: CATEGORY, prompt: "ambiente minimo, aria pulita, nessun elemento extra" },
{ id: "hyper-atm-ambiente-082", title: "Ambiente intimo", summary: "Vicino.", area: AREA, category: CATEGORY, prompt: "atmosfera intima, luce morbida, aria tranquilla realistica" },
{ id: "hyper-atm-ambiente-083", title: "Ambiente teso", summary: "Davvero drammatico.", area: AREA, category: CATEGORY, prompt: "ambiente teso, contrasto moderato, atmosfera credibile" },
{ id: "hyper-atm-ambiente-084", title: "Atmosfera allegra", summary: "Luminoso.", area: AREA, category: CATEGORY, prompt: "atmosfera allegra, luce naturale, colori puliti senza oversat" },
{ id: "hyper-atm-ambiente-085", title: "Ambiente nostalgico", summary: "Un film leggero.", area: AREA, category: CATEGORY, prompt: "ambiente nostalgico, toni morbidi, grano sottile (se applicabile)" },
{ id: "hyper-atm-ambiente-086", title: "Atmosfera precoce", summary: "Silenzio.", area: AREA, category: CATEGORY, prompt: "realistico mattina presto, luce minima, atmosfera calma" },
{ id: "hyper-atm-ambiente-087", title: "Atmosfera pomeridiana", summary: "Normale.", area: AREA, category: CATEGORY, prompt: "sera naturale, luce stabile, atmosfera realistica neutrale" },
{ id: "hyper-atm-ambiente-088", title: "Ambiente", summary: "Pratico.", area: AREA, category: CATEGORY, prompt: "ambiente ufficio realistico, luce mista controllata, nessun verde raro" },
{ id: "hyper-atm-ambiente-089", title: "Ambiente di palestra", summary: "Sudore reale.", area: AREA, category: CATEGORY, prompt: "palestra realistica, umidità / sudore sottile, aria calda" },
{ id: "hyper-atm-ambiente-090", title: "Ambiente urbano", summary: "Rumore visivo controllato.", area: AREA, category: CATEGORY, prompt: "strada realistica con la vita, lieve fare, nessun caos artificiale" },

{ id: "hyper-atm-ambiente-091", title: "Nessuna particelle eccessiva", summary: "Evita la fantasia.", area: AREA, category: CATEGORY, prompt: "senza particelle eccessive, tutte sottili e fotografiche" },
{ id: "hyper-atm-ambiente-092", title: "Nessuna fase del tipo di fumo", summary: "Nessun concerto.", area: AREA, category: CATEGORY, prompt: "evitare il fumo di tipo scenico, mantenere la dispersione naturale" },
{ id: "hyper-atm-ambiente-093", title: "Nessun falso volumetrico", summary: "Vero.", area: AREA, category: CATEGORY, prompt: "evitare false densità volumetrica, bassa e costante" },
{ id: "hyper-atm-ambiente-094", title: "No neon Cyberpunk", summary: "Nessuna caricatura.", area: AREA, category: CATEGORY, prompt: "evitare neon esagerato cyberpunk, mantenere la luce realistica" },
{ id: "hyper-atm-ambiente-095", title: "Dettaglio atmosferico reale", summary: "Vicino.", area: AREA, category: CATEGORY, prompt: "dettagli atmosferici realistici, autentico senso di luogo" },
{ id: "hyper-atm-ambiente-096", title: "Profondità dell'aria", summary: "Distanza.", area: AREA, category: CATEGORY, prompt: "profondità atmosferica in distanza, tono e contrasto gradualmente diminuiscono" },
{ id: "hyper-atm-ambiente-097", title: "Prospettiva con nebbia", summary: "Lentamente via.", area: AREA, category: CATEGORY, prompt: "elementi distanti ammorbiditi dall'atmosfera, realistici" },
{ id: "hyper-atm-ambiente-098", title: "Ambiente umido urbano", summary: "City.", area: AREA, category: CATEGORY, prompt: "ambiente urbano umido, riflessi sottili, aria pesante" },
{ id: "hyper-atm-ambiente-099", title: "Ambiente freddo secco", summary: "Clarity.", area: AREA, category: CATEGORY, prompt: "ambiente freddo asciutto, aria chiara, ombre pulite" },
{ id: "hyper-atm-ambiente-100", title: "Ambiente umido caldo", summary: "Tropicale.", area: AREA, category: CATEGORY, prompt: "ambiente umido caldo, nebbia morbida, condensa sottile" }];