// src/lib/prompts/hyperrealism-text/camara.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Macchina fotografica";
const CATEGORY = "Lenti";

export const hyperrealismTextPromptsCamara = [
{ id: "hyper-camara-lentes-001", title: "documentario 35mm", summary: "Prospettive naturali.", area: AREA, category: CATEGORY, prompt: "35mm, stile documentario, prospettiva naturale" },
{ id: "hyper-camara-lentes-002", title: "50 millimetri classico", summary: "Bilancia realistica.", area: AREA, category: CATEGORY, prompt: "50mm, look classico, proporzioni reali" },
{ id: "hyper-camara-lentes-003", title: "ritratto di 85 mm", summary: "Bella compressione.", area: AREA, category: CATEGORY, prompt: "85mm, compressione sottile, ritratto editoriale" },
{ id: "hyper-camara-lentes-004", title: "105mm macro", summary: "Dettagli estremi.", area: AREA, category: CATEGORY, prompt: "macro 105mm, microdetail visibile, nitidezza realistica" },
{ id: "hyper-camara-lentes-005", title: "24mm angolare moderata", summary: "Niente sovrappeso.", area: AREA, category: CATEGORY, prompt: "24mm, grande angolo moderato, linee diritte naturali" },
{ id: "hyper-camara-lentes-006", title: "28 millimetri strada", summary: "Una vera strada.", area: AREA, category: CATEGORY, prompt: "28mm, fotografia di strada, cornice dinamica" },
{ id: "hyper-camara-lentes-007", title: "pellicola morbida 70mm", summary: "Compressione media.", area: AREA, category: CATEGORY, prompt: "70mm, compressione media, aspetto cinematografico" },
{ id: "hyper-camara-lentes-008", title: "135 millimetri ritratto tv", summary: "Sfondo compresso.", area: AREA, category: CATEGORY, prompt: "135mm, ritratto tv, sfondo compresso realistico" },
{ id: "hyper-camara-lentes-009", title: "isolamento 200mm", summary: "Argomento separato.", area: AREA, category: CATEGORY, prompt: "200mm, teletarget, soggetto isolato, compressione effettiva" },
{ id: "hyper-camara-lentes-010", title: "Lente standard pulita", summary: "Nessuna strana distorsione.", area: AREA, category: CATEGORY, prompt: "lente standard, prospettiva naturale, geometria corretta" },

{ id: "hyper-camara-lentes-011", title: "Bassa distorsione", summary: "Uova pulite.", area: AREA, category: CATEGORY, prompt: "bassa distorsione, linee rette, senza curvatura" },
{ id: "hyper-camara-lentes-012", title: "Nessun occhio di pesce", summary: "Niente curva.", area: AREA, category: CATEGORY, prompt: "senza occhi di pesce, senza deformazione estrema" },
{ id: "hyper-camara-lentes-013", title: "Bokeh naturale", summary: "Un errore credibile.", area: AREA, category: CATEGORY, prompt: "bokeh naturale, difetti progressivi, senza tagli" },
{ id: "hyper-camara-lentes-014", title: "DOF media", summary: "Soggetto chiaro, sfondo morbido.", area: AREA, category: CATEGORY, prompt: "profondità media del campo, soggetto affilato, fondo morbido" },
{ id: "hyper-camara-lentes-015", title: "Basso", summary: "Approccio selettivo.", area: AREA, category: CATEGORY, prompt: "profondità di campo bassa, messa a fuoco precisa, fondo cremoso" },
{ id: "hyper-camara-lentes-016", title: "Alto DOF", summary: "Tutto a posto.", area: AREA, category: CATEGORY, prompt: "profondità di campo alto, nulla da aereo a aereo" },
{ id: "hyper-camara-lentes-017", title: "Approccio agli occhi", summary: "Un vero ritratto.", area: AREA, category: CATEGORY, prompt: "approccio all'occhio dominante, nitidezza naturale" },
{ id: "hyper-camara-lentes-018", title: "Approccio del prodotto", summary: "Pacchetti.", area: AREA, category: CATEGORY, prompt: "attenzione ai bordi del prodotto, texture visibile" },
{ id: "hyper-camara-lentes-019", title: "Focus", summary: "Capelli veri.", area: AREA, category: CATEGORY, prompt: "focalizzarsi in primo piano, cadere a fuoco reale" },
{ id: "hyper-camara-lentes-020", title: "Microcontrasto reale", summary: "Dettaglio senza HDR.", area: AREA, category: CATEGORY, prompt: "microcontrasto realistico, dettaglio fine, senza HDR aggressivo" },

{ id: "hyper-camara-lentes-021", title: "Grano sottile", summary: "Texture fotografica.", area: AREA, category: CATEGORY, prompt: "sottile, naturale grano fotografico" },
{ id: "hyper-camara-lentes-022", title: "Nessun overfocus", summary: "Nitrity organico.", area: AREA, category: CATEGORY, prompt: "senza affilare eccessivamente, nitidez naturale" },
{ id: "hyper-camara-lentes-023", title: "Nitrity organico", summary: "Niente halos.", area: AREA, category: CATEGORY, prompt: "nitidez organico, no halos, texture reale" },
{ id: "hyper-camara-lentes-024", title: "Nessuna sfocatura inconsistente", summary: "Evita gli artefatti.", area: AREA, category: CATEGORY, prompt: "senza disapproccio incoerente, senza sfocatura artificiale" },
{ id: "hyper-camara-lentes-025", title: "Esposizione bilanciata", summary: "Gamma completa.", area: AREA, category: CATEGORY, prompt: "esposizione equilibrata, dettaglio in ombre e luci" },
{ id: "hyper-camara-lentes-026", title: "Vigneto minimo", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "molto sottile o nil, aspetto naturale" },
{ id: "hyper-camara-lentes-027", title: "Vigna morbida", summary: "Concentrazione visiva.", area: AREA, category: CATEGORY, prompt: "morbido, sottile, non ovvio" },
{ id: "hyper-camara-lentes-028", title: "Bilancia coerente", summary: "Una vera distanza.", area: AREA, category: CATEGORY, prompt: "distanza focale coerente con la scena, scala realistica" },
{ id: "hyper-camara-lentes-029", title: "Prospettive umane", summary: "Occhio umano.", area: AREA, category: CATEGORY, prompt: "prospettiva umana naturale, proporzioni corrette" },
{ id: "hyper-camara-lentes-030", title: "Angolo di livello degli occhi", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "angolo all'altezza dell'occhio, composizione naturale" },

{ id: "hyper-camara-lentes-031", title: "Livello medio", summary: "Equilibrato.", area: AREA, category: CATEGORY, prompt: "piano medio, struttura bilanciata, proporzione reale" },
{ id: "hyper-camara-lentes-032", title: "Primo piano facciale", summary: "Un vero dettaglio.", area: AREA, category: CATEGORY, prompt: "primo piano facciale, dettaglio realistico della pelle" },
{ id: "hyper-camara-lentes-033", title: "Livello generale", summary: "Ambiente completo.", area: AREA, category: CATEGORY, prompt: "piano generale, linee coerenti, scala umana" },
{ id: "hyper-camara-lentes-034", title: "Angolo 3 / 4", summary: "Profondità.", area: AREA, category: CATEGORY, prompt: "angolo 3 / 4, profondità naturale, nessuna deformazione" },
{ id: "hyper-camara-lentes-035", title: "Luce contraffatta", summary: "Subtle.", area: AREA, category: CATEGORY, prompt: "proporzioni leggere contrappeso, stabile e realistico" },
{ id: "hyper-camara-lentes-036", title: "Un po' di luce", summary: "Subtle.", area: AREA, category: CATEGORY, prompt: "geometria leggera tritata, stabile e realistica" },
{ id: "hyper-camara-lentes-037", title: "Aberrazione minima", summary: "Uova pulite.", area: AREA, category: CATEGORY, prompt: "aberrazione cromatica minima, bordi puliti" },
{ id: "hyper-camara-lentes-038", title: "Real sottile aberrazione", summary: "Micro realismo.", area: AREA, category: CATEGORY, prompt: "aberrazione cromatica molto mite (realistica)" },
{ id: "hyper-camara-lentes-039", title: "Non morirò", summary: "Tessili OK.", area: AREA, category: CATEGORY, prompt: "senza bagnato, senza rari modelli in vestiti / tessuto" },
{ id: "hyper-camara-lentes-040", title: "Scafo di movimento minimo", summary: "Solo se si applica.", area: AREA, category: CATEGORY, prompt: "sfocatura minima realistica del movimento (se c'è movimento)" },

{ id: "hyper-camara-lentes-041", title: "Dettaglio in ombre", summary: "Nero, non spun.", area: AREA, category: CATEGORY, prompt: "dettaglio in ombre, nero non imbottito" },
{ id: "hyper-camara-lentes-042", title: "Dettaglio in evidenza", summary: "Non bruciare.", area: AREA, category: CATEGORY, prompt: "dettaglio in highlights, roll-off soft" },
{ id: "hyper-camara-lentes-043", title: "Bilancia bianca naturale", summary: "Stupidi credibili.", area: AREA, category: CATEGORY, prompt: "equilibrio bianco naturale, toni cutanei credibili" },
{ id: "hyper-camara-lentes-044", title: "Nessuna saturazione extra", summary: "Colore reale.", area: AREA, category: CATEGORY, prompt: "senza saturazione eccessiva, colore realistico" },
{ id: "hyper-camara-lentes-045", title: "Telaio pulito", summary: "Un vero minimo.", area: AREA, category: CATEGORY, prompt: "struttura centrale pulita, composizione realistica semplice" },
{ id: "hyper-camara-lentes-046", title: "Regola di terze parti", summary: "Classico.", area: AREA, category: CATEGORY, prompt: "composizione regola del terzo, equilibrio naturale" },
{ id: "hyper-camara-lentes-047", title: "Simmetria controllata", summary: "Ordine visivo.", area: AREA, category: CATEGORY, prompt: "simmetria sottile, linee pulite, realismo" },
{ id: "hyper-camara-lentes-048", title: "Linee guida", summary: "Guarda la guida.", area: AREA, category: CATEGORY, prompt: "linee naturali principali, senza geometria impossibile" },
{ id: "hyper-camara-lentes-049", title: "Incontro con l'aria", summary: "Respira.", area: AREA, category: CATEGORY, prompt: "realistico spazio negativo, cornice con aria" },
{ id: "hyper-camara-lentes-050", title: "Taglio editoriale", summary: "Rivista.", area: AREA, category: CATEGORY, prompt: "taglio editoriale, cornice lucida, realistico" },

{ id: "hyper-camara-lentes-051", title: "Corpo completo 35mm", summary: "Tutto il corpo naturale.", area: AREA, category: CATEGORY, prompt: "35mm, intero piano del corpo, proporzioni reali" },
{ id: "hyper-camara-lentes-052", title: "Corpo intero 50mm", summary: "Più naturale.", area: AREA, category: CATEGORY, prompt: "50mm, corpo intero, prospettiva stabile" },
{ id: "hyper-camara-lentes-053", title: "Ritratto 85mm con bokeh", summary: "Sfondo cremoso.", area: AREA, category: CATEGORY, prompt: "85mm, bokeh naturale, approccio preciso" },
{ id: "hyper-camara-lentes-054", title: "Tessuto morbido 135 mm", summary: "Bella compressione.", area: AREA, category: CATEGORY, prompt: "135mm, compressione morbida, sfondo calmo" },
{ id: "hyper-camara-lentes-055", title: "Macro reale", summary: "Niente plastica.", area: AREA, category: CATEGORY, prompt: "realistico macro, texture autentica, nessun look CGI" },
{ id: "hyper-camara-lentes-056", title: "28 millimetri strada", summary: "Realismo urbano.", area: AREA, category: CATEGORY, prompt: "28mm, strada, movimento sottile, realismo" },
{ id: "hyper-camara-lentes-057", title: "Interno 35mm", summary: "Stanza vera.", area: AREA, category: CATEGORY, prompt: "35mm, interno, linee rette, look naturale" },
{ id: "hyper-camara-lentes-058", title: "Interni moderati 24 mm", summary: "Ampio non deformato.", area: AREA, category: CATEGORY, prompt: "24mm moderato, interno, senza estrema distorsione" },
{ id: "hyper-camara-lentes-059", title: "Prodotto 70mm", summary: "Premium Packshot.", area: AREA, category: CATEGORY, prompt: "70mm, prodotto, bordi taglienti, texture visibile" },
{ id: "hyper-camara-lentes-060", title: "Prodotto 105mm", summary: "Dettaglio.", area: AREA, category: CATEGORY, prompt: "105mm, prodotto, dettaglio estremo, messa a fuoco pulita" },

{ id: "hyper-camara-lentes-061", title: "F naturale / 2.8", summary: "Bokeh credibile.", area: AREA, category: CATEGORY, prompt: "tipo apertura f / 2.8, bokeh naturale, senza tagli" },
{ id: "hyper-camara-lentes-062", title: "F / 1.8 controllato", summary: "La DOF e' davvero in crisi.", area: AREA, category: CATEGORY, prompt: "tipo di apertura f / 1.8 (controllato), approccio preciso" },
{ id: "hyper-camara-lentes-063", title: "F / 5.6 notide", summary: "Più profondità.", area: AREA, category: CATEGORY, prompt: "tipo apertura f / 5.6, nitrity coerente" },
{ id: "hyper-camara-lentes-064", title: "F / 8 paesaggio", summary: "In aereo.", area: AREA, category: CATEGORY, prompt: "tipo apertura f / 8, ampia profondità, dettaglio" },
{ id: "hyper-camara-lentes-065", title: "ISO basso", summary: "Pulito.", area: AREA, category: CATEGORY, prompt: "Bassa ISO, minimo rumore, dettaglio realistico" },
{ id: "hyper-camara-lentes-066", title: "Rumore discreto", summary: "La realtà.", area: AREA, category: CATEGORY, prompt: "realistico, non aggressivo rumore della luce digitale" },
{ id: "hyper-camara-lentes-067", title: "Shutter veloce", summary: "Congela.", area: AREA, category: CATEGORY, prompt: "chiusura rapida, nitidezza senza trepidazione" },
{ id: "hyper-camara-lentes-068", title: "Shutter controllato lento", summary: "Una vera sfocatura.", area: AREA, category: CATEGORY, prompt: "arresto lento controllato, sfocatura di movimento realistico" },
{ id: "hyper-camara-lentes-069", title: "Stabilizzazione morbida", summary: "Tenente.", area: AREA, category: CATEGORY, prompt: "stabilizzazione morbida, palmare naturale" },
{ id: "hyper-camara-lentes-070", title: "Tripité look", summary: "Pro statico.", area: AREA, category: CATEGORY, prompt: "stabile tripid-tipo di presa, composizione solida" },

{ id: "hyper-camara-lentes-071", title: "Taglio 4: 3", summary: "Classico.", area: AREA, category: CATEGORY, prompt: "cornice 4: 3, classica estetica fotografica" },
{ id: "hyper-camara-lentes-072", title: "Taglio 3: 2", summary: "Foto standard.", area: AREA, category: CATEGORY, prompt: "cornice 3: 2, sensazione DSLR, realistico" },
{ id: "hyper-camara-lentes-073", title: "Taglio 1: 1", summary: "Square.", area: AREA, category: CATEGORY, prompt: "cornice 1: 1, composizione pulita e realistica" },
{ id: "hyper-camara-lentes-074", title: "Taglio 16: 9", summary: "Cinematica.", area: AREA, category: CATEGORY, prompt: "cornice 16: 9, guarda la fotografia naturale" },
{ id: "hyper-camara-lentes-075", title: "Ottura rotante zero", summary: "Nessuna deformazione.", area: AREA, category: CATEGORY, prompt: "nessuna deformazione dell'otturatore, geometria stabile" },
{ id: "hyper-camara-lentes-076", title: "Nessun banding", summary: "Soffici gradienti.", area: AREA, category: CATEGORY, prompt: "sfumature morbide, senza bande, tono naturale" },
{ id: "hyper-camara-lentes-077", title: "No hales", summary: "Bordi naturali.", area: AREA, category: CATEGORY, prompt: "senza ali di messa a fuoco, bordi naturali" },
{ id: "hyper-camara-lentes-078", title: "Nessuna posterizzazione", summary: "Colore reale.", area: AREA, category: CATEGORY, prompt: "senza posterizzazione, toni morbidi realistici" },
{ id: "hyper-camara-lentes-079", title: "Nessun artefatto AI", summary: "Pulito.", area: AREA, category: CATEGORY, prompt: "nessun artefatto, nessuna texture ripetuta, nessun glitch" },
{ id: "hyper-camara-lentes-080", title: "Struttura del sensore", summary: "Foto vera.", area: AREA, category: CATEGORY, prompt: "reale sensazione di sensore, fine, dettaglio naturale" },

{ id: "hyper-camara-lentes-081", title: "Respirazione di approccio zero", summary: "Un approccio stabile.", area: AREA, category: CATEGORY, prompt: "un approccio stabile, senza rare modifiche nel DOF" },
{ id: "hyper-camara-lentes-082", title: "Separazione DCF", summary: "Il soggetto si distingue.", area: AREA, category: CATEGORY, prompt: "soggetto di separazione di fondo per DOF naturale" },
{ id: "hyper-camara-lentes-083", title: "Compressione naturale", summary: "Niente schiacciamento.", area: AREA, category: CATEGORY, prompt: "compressione naturale, proporzioni credibili" },
{ id: "hyper-camara-lentes-084", title: "Nessuna prospettiva impossibile", summary: "Geometria reale.", area: AREA, category: CATEGORY, prompt: "senza una prospettiva impossibile, linee coerenti" },
{ id: "hyper-camara-lentes-085", title: "Piano macro dettaglio", summary: "Molto vicino.", area: AREA, category: CATEGORY, prompt: "dettaglio macro piatto, texture autentica, microimperfezioni" },
{ id: "hyper-camara-lentes-086", title: "Dettaglio del prodotto", summary: "E-commerce.", area: AREA, category: CATEGORY, prompt: "dettaglio prodotto piatto, bordi taglienti, riflessi controllati" },
{ id: "hyper-camara-lentes-087", title: "Fondo fuori dal fuoco reale", summary: "Bokeh graduale.", area: AREA, category: CATEGORY, prompt: "sfondo di fuoco graduale, senza tagli duri" },
{ id: "hyper-camara-lentes-088", title: "Focus nella texture", summary: "Materiale visibile.", area: AREA, category: CATEGORY, prompt: "focus sulla texture, visibile, microdetail naturale" },
{ id: "hyper-camara-lentes-089", title: "Edizione minima", summary: "Niente filtri.", area: AREA, category: CATEGORY, prompt: "edizione minima, guardare foto reale, senza filtri aggressivi" },
{ id: "hyper-camara-lentes-090", title: "Colore sfumato morbido", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "colore sfumato, contrasto controllato, realistico" },

{ id: "hyper-camara-lentes-091", title: "Chiarezza moderata", summary: "Dettaglio senza durezza.", area: AREA, category: CATEGORY, prompt: "chiarezza moderata, dettaglio realistico, senza durezza" },
{ id: "hyper-camara-lentes-092", title: "Senza HDR", summary: "Niente di esagerato.", area: AREA, category: CATEGORY, prompt: "senza HDR esagerato, gamma naturale" },
{ id: "hyper-camara-lentes-093", title: "Approccio continuo", summary: "Soggetto stabile.", area: AREA, category: CATEGORY, prompt: "continuo approccio stabile, argomento sempre chiaro" },
{ id: "hyper-camara-lentes-094", title: "Approccio tempestivo", summary: "Precisione.", area: AREA, category: CATEGORY, prompt: "punto singolo, massima precisione" },
{ id: "hyper-camara-lentes-095", title: "Guarda RAW", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "senso RAW, colore naturale, dettaglio autentico" },
{ id: "hyper-camara-lentes-096", title: "Nessuna compressione brutta", summary: "Pulito.", area: AREA, category: CATEGORY, prompt: "nessun dispositivo di compressione, dettaglio pulito" },
{ id: "hyper-camara-lentes-097", title: "Ombre pulite", summary: "Non fare i bagagli.", area: AREA, category: CATEGORY, prompt: "ombre pulite, nessun imballaggio, rumore controllato" },
{ id: "hyper-camara-lentes-098", title: "In evidenza morbida", summary: "Togliti.", area: AREA, category: CATEGORY, prompt: "soft highlight, roll-off naturale, senza clipping" },
{ id: "hyper-camara-lentes-099", title: "Tipo di obiettivo reale nitdez", summary: "Non digitale.", area: AREA, category: CATEGORY, prompt: "nitidez tipo obiettivo reale, non digitale, nessun halos" },
{ id: "hyper-camara-lentes-100", title: "Combo fotocamera pro", summary: "Il pacchetto finale.", area: AREA, category: CATEGORY, prompt: "lente realistica, DOF naturale, grano sottile, nitidezza organica" }];