// src/lib/prompts/hyperrealism-text/color.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Colore";
const CATEGORY = "Bilancio";

export const hyperrealismTextPromptsColor = [
{ id: "hyper-col-balance-001", title: "Bilancio neutro", summary: "Colore reale senza dominante.", area: AREA, category: CATEGORY, prompt: "equilibrio bianco neutro, colori naturali, senza dominante" },
{ id: "hyper-col-balance-002", title: "Caldo WB morbido", summary: "Il calore realistico.", area: AREA, category: CATEGORY, prompt: "morbida temperatura calda, pelle credibile, senza eccessiva giallastra" },
{ id: "hyper-col-balance-003", title: "WB freddo morbido", summary: "La freschezza realistica.", area: AREA, category: CATEGORY, prompt: "temperatura fredda morbida, bianca pulita, non blu artificiale" },
{ id: "hyper-col-balance-004", title: "Toni pelle naturale", summary: "Priorita' della pelle.", area: AREA, category: CATEGORY, prompt: "toni naturali e credibili della pelle, senza magenta / verde raro" },
{ id: "hyper-col-balance-005", title: "Saturazione contenuta", summary: "Nessun aspetto HDR.", area: AREA, category: CATEGORY, prompt: "saturazione contenuta, contrasto realistico, senza HDR esagerato" },
{ id: "hyper-col-balance-006", title: "Contrasto morbido", summary: "Editoriale.", area: AREA, category: CATEGORY, prompt: "contrasto morbido, ombre aperte, roll-off naturale in luci" },
{ id: "hyper-col-balance-007", title: "Contralto medio", summary: "Foto standard.", area: AREA, category: CATEGORY, prompt: "realistico contrasto medio, punti neri controllati, nessuna crepa" },
{ id: "hyper-col-balance-008", title: "Luci protette", summary: "Niente bruciature.", area: AREA, category: CATEGORY, prompt: "luci ad alta protezione, bianco con dettaglio, senza clipping" },
{ id: "hyper-col-balance-009", title: "Ombre pulite", summary: "Niente fango.", area: AREA, category: CATEGORY, prompt: "ombre pulite, niente 'mud' cromatico, dettagli conservati" },
{ id: "hyper-col-balance-010", title: "Nero naturale", summary: "Niente nero puro.", area: AREA, category: CATEGORY, prompt: "nero naturale (non nero puro), dettaglio sottile in ombre" },

{ id: "hyper-col-balance-011", title: "Valutazione film sottile", summary: "Niente esagerazioni.", area: AREA, category: CATEGORY, prompt: "sottile colore sfumatura pellicola, senza eccessiva teal- arancione" },
{ id: "hyper-col-balance-012", title: "Teal-orange MUY mite", summary: "Solo un tocco.", area: AREA, category: CATEGORY, prompt: "arancio leggero, pelle naturale, ombre appena fredde" },
{ id: "hyper-col-balance-013", title: "Guarda la rivista editoriale", summary: "Premium.", area: AREA, category: CATEGORY, prompt: "rivista editorial look, colori naturali, soft separazione" },
{ id: "hyper-col-balance-014", title: "Approccio documentario", summary: "Molto crudo.", area: AREA, category: CATEGORY, prompt: "look documentario, colori onesti, contrasto moderato" },
{ id: "hyper-col-balance-015", title: "Guarda e-commerce pulito", summary: "Vero prodotto.", area: AREA, category: CATEGORY, prompt: "vero colore del prodotto, bianco neutro, senza dominante" },
{ id: "hyper-col-balance-016", title: "Cercare cibo naturale", summary: "Molto veloce.", area: AREA, category: CATEGORY, prompt: "colore naturale nel cibo, delicato equilibrio caldo, senza falsa saturazione" },
{ id: "hyper-col-balance-017", title: "Real look urbano", summary: "Strada realistica.", area: AREA, category: CATEGORY, prompt: "colori urbani realistici, calcestruzzo e metallo naturale, senza neon" },
{ id: "hyper-col-balance-018", title: "Ortaggi naturali", summary: "Evitare radioattivi.", area: AREA, category: CATEGORY, prompt: "verde naturale, nessun verde radioattivo, variazione organica" },
{ id: "hyper-col-balance-019", title: "Piastrelle naturali", summary: "Niente cian strano.", area: AREA, category: CATEGORY, prompt: "blu naturale, senza ciano artificiale, cielo con reale pendenza" },
{ id: "hyper-col-balance-020", title: "Rosso controllato", summary: "Niente clip.", area: AREA, category: CATEGORY, prompt: "rosso controllato, senza clipping, intenso dettaglio rosso" },

{ id: "hyper-col-balance-021", title: "Evitare di bandire", summary: "Degradato pulito.", area: AREA, category: CATEGORY, prompt: "morbido degradato senza bande, transizioni pulite" },
{ id: "hyper-col-balance-022", title: "Evitare rare saturazioni selettive", summary: "Conformità.", area: AREA, category: CATEGORY, prompt: "saturazione costante, nessun colore 'sacco' artificialmente" },
{ id: "hyper-col-balance-023", title: "Evitare il sovrasfruttamento e halos", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "no hales per focus, nitidezza naturale, bordi puliti" },
{ id: "hyper-col-balance-024", title: "Bianco pulito", summary: "Niente giallo / verde.", area: AREA, category: CATEGORY, prompt: "bianco pulito, nessun verde / giallo dominante, dettagli conservati" },
{ id: "hyper-col-balance-025", title: "Grigio neutro", summary: "Riferimento.", area: AREA, category: CATEGORY, prompt: "grigio neutro, senza dominante, contrasto realistico" },
{ id: "hyper-col-balance-026", title: "(dark) toni della pelle corretti", summary: "Niente cenere.", area: AREA, category: CATEGORY, prompt: "realistica pelle scura, senza 'sh', subtoni credibili" },
{ id: "hyper-col-balance-027", title: "(clear) toni cutanei corretti", summary: "Nessuna rosa artificiale.", area: AREA, category: CATEGORY, prompt: "pelle chiara, senza rosa artificiale, consistenza naturale" },
{ id: "hyper-col-balance-028", title: "Sottotoni bilanciati", summary: "Niente verde / magenta.", area: AREA, category: CATEGORY, prompt: "sottotoni bilanciati, evitare dominante verde o pelle magenta" },
{ id: "hyper-col-balance-029", title: "Ombre fredde naturali", summary: "Non lo fanno.", area: AREA, category: CATEGORY, prompt: "ombre naturali leggermente fredde, senza cian aggressivo / teal" },
{ id: "hyper-col-balance-030", title: "Luci calde naturali", summary: "Non arancione.", area: AREA, category: CATEGORY, prompt: "luci naturali leggermente calde, senza arancio eccessivo" },

{ id: "hyper-col-balance-031", title: "Palestra di terra", summary: "Organico.", area: AREA, category: CATEGORY, prompt: "tavolozza di terra naturale (beige, marrone, oliva), bassa saturazione" },
{ id: "hyper-col-balance-032", title: "Tavolozza neutra fredda", summary: "Tecnologia pulita.", area: AREA, category: CATEGORY, prompt: "tavolozza fredda neutra (grande, blu morbido), bianco pulito" },
{ id: "hyper-col-balance-033", title: "Tavolozza calda neutro", summary: "Cozy.", area: AREA, category: CATEGORY, prompt: "tavolozza calda neutra (creas, ambra morbida), pelle naturale" },
{ id: "hyper-col-balance-034", title: "Tavolozza monocromatica", summary: "Elegante.", area: AREA, category: CATEGORY, prompt: "sottile tavolozza monocromatica, variazione tonale realistica" },
{ id: "hyper-col-balance-035", title: "Integratore morbido", summary: "Atento.", area: AREA, category: CATEGORY, prompt: "morbidi colori complementari, accento controllato, senza neon" },
{ id: "hyper-col-balance-036", title: "Evento unico", summary: "Concentrati.", area: AREA, category: CATEGORY, prompt: "accento di colore singolo, riposo neutro, sensazione premium" },
{ id: "hyper-col-balance-037", title: "Bassa saturazione", summary: "Cinema / arte.", area: AREA, category: CATEGORY, prompt: "bassa saturazione, toni naturali, contrasto morbido" },
{ id: "hyper-col-balance-038", title: "Saturazione media reale", summary: "Foto standard.", area: AREA, category: CATEGORY, prompt: "saturazione media realistica, nessun oversat, buon equilibrio" },
{ id: "hyper-col-balance-039", title: "Microcontrasto sottile", summary: "Dettaglio senza HDR.", area: AREA, category: CATEGORY, prompt: "microcontrasto sottile, dettaglio reale, nessun effetto HDR" },
{ id: "hyper-col-balance-040", title: "Curva morbida", summary: "Togliti.", area: AREA, category: CATEGORY, prompt: "curva tonale morbida, roll-off naturale, ombre con dettaglio" },

{ id: "hyper-col-balance-041", title: "Non guardare 'AI'", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "evitare look 'AI': colori rari, pelle di plastica, contrasti artificiali" },
{ id: "hyper-col-balance-042", title: "Nessuna chiarezza eccessiva", summary: "Una vera texture.", area: AREA, category: CATEGORY, prompt: "senza eccessiva chiarezza, texture realistica, pelle naturale" },
{ id: "hyper-col-balance-043", title: "Nessuna vibrazione aggressivo", summary: "Controllo.", area: AREA, category: CATEGORY, prompt: "senza vibrazioni aggressive, saturazione naturale, toni cutanei corretti" },
{ id: "hyper-col-balance-044", title: "Secchi di torta reali", summary: "Morbido.", area: AREA, category: CATEGORY, prompt: "toni pastello reali, nessun senso di illustrazione" },
{ id: "hyper-col-balance-045", title: "Neutralità della carta", summary: "E-commerce / studio.", area: AREA, category: CATEGORY, prompt: "studio / tipo di carta neutralità, obiettivi coerenti" },
{ id: "hyper-col-balance-046", title: "Controllo dominante verde", summary: "Pelle.", area: AREA, category: CATEGORY, prompt: "verde, pelle naturale, bianco pulito" },
{ id: "hyper-col-balance-047", title: "Magenta controllo dominante", summary: "Pelle.", area: AREA, category: CATEGORY, prompt: "master magenta corretto, pelle naturale, ombre pulite" },
{ id: "hyper-col-balance-048", title: "Controllo dominante giallo", summary: "Non seppia.", area: AREA, category: CATEGORY, prompt: "evitare il giallo dominante, calore realistico, senza seppia" },
{ id: "hyper-col-balance-049", title: "Controllo dominante blu", summary: "Non il ghiaccio.", area: AREA, category: CATEGORY, prompt: "evitare la pelle blu dominante, bianca neutrale, credibile" },
{ id: "hyper-col-balance-050", title: "Fedeltà al colore", summary: "Fedele alla realtà.", area: AREA, category: CATEGORY, prompt: "fedeltà del colore, toni coerenti con la realtà" },

{ id: "hyper-col-balance-051", title: "Tono di pelle roll-off", summary: "Luci cutanee.", area: AREA, category: CATEGORY, prompt: "naturale roll-off in alte luci della pelle, non bruciato" },
{ id: "hyper-col-balance-052", title: "Rosa naturale sulle guance", summary: "Subtle.", area: AREA, category: CATEGORY, prompt: "blushing naturale sottile, senza trucco eccessivo" },
{ id: "hyper-col-balance-053", title: "Labbra naturali", summary: "Niente neon.", area: AREA, category: CATEGORY, prompt: "colore labbro naturale, senza falsa saturazione" },
{ id: "hyper-col-balance-054", title: "Denti naturali", summary: "Niente bianco brillante.", area: AREA, category: CATEGORY, prompt: "denti bianchi naturali, non fluorescenti" },
{ id: "hyper-col-balance-055", title: "Occhi naturali", summary: "Niente neon iris.", area: AREA, category: CATEGORY, prompt: "iris con colore naturale, senza neon, riflessi coerenti" },
{ id: "hyper-col-balance-056", title: "Capelli veri", summary: "Niente neri imbottiti.", area: AREA, category: CATEGORY, prompt: "capelli con dettaglio tonale, no nero, incollato" },
{ id: "hyper-col-balance-057", title: "Metallo reale", summary: "Riflessioni giuste.", area: AREA, category: CATEGORY, prompt: "metalli reali, senza riflessi impossibili" },
{ id: "hyper-col-balance-058", title: "Legno reale", summary: "Non arancione.", area: AREA, category: CATEGORY, prompt: "legno con toni naturali, senza arancio saturo" },
{ id: "hyper-col-balance-059", title: "Real calcestruzzo", summary: "Grigio destro.", area: AREA, category: CATEGORY, prompt: "cemento con reale grigio, variazione naturale, senza verde" },
{ id: "hyper-col-balance-060", title: "Verde vero fogliame", summary: "Varietà.", area: AREA, category: CATEGORY, prompt: "fogliame con varietà di verde, senza tono uniforme" },

{ id: "hyper-col-balance-061", title: "Cielo reale", summary: "Gradente naturale.", area: AREA, category: CATEGORY, prompt: "cielo con gradiente naturale, senza fasciatura, colore reale" },
{ id: "hyper-col-balance-062", title: "Tempo reale d'oro", summary: "Un vero calore.", area: AREA, category: CATEGORY, prompt: "tempo dorato realistico, calore naturale, ombre morbide" },
{ id: "hyper-col-balance-063", title: "Tempo reale blu", summary: "Blu morbido.", area: AREA, category: CATEGORY, prompt: "tempo blu realistico, blu morbido, caldo, luci spot" },
{ id: "hyper-col-balance-064", title: "Cloud reale", summary: "Fuse.", area: AREA, category: CATEGORY, prompt: "luce nuvolosa, colori leggermente spenti, realistici" },
{ id: "hyper-col-balance-065", title: "Real tungsteno interno", summary: "Caldo dentro.", area: AREA, category: CATEGORY, prompt: "interno con luce di tungsteno realistica, senza giallo estremo" },
{ id: "hyper-col-balance-066", title: "LED reale", summary: "Niente di strano.", area: AREA, category: CATEGORY, prompt: "illuminazione LED realistica, senza verde dominante, bianco pulito" },
{ id: "hyper-col-balance-067", title: "Neon reale (controllato)", summary: "Niente cibernetica.", area: AREA, category: CATEGORY, prompt: "neon controllato effettivo, esposizione corretta, senza saturazione assurda" },
{ id: "hyper-col-balance-068", title: "Indietro", summary: "Concircolo.", area: AREA, category: CATEGORY, prompt: "contrasto realistico, dettagli conservati, minimo flare" },
{ id: "hyper-col-balance-069", title: "Ombre morbide", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "ombre morbide naturali, senza neri schiacciati" },
{ id: "hyper-col-balance-070", title: "Ombre marcate", summary: "Forte sole.", area: AREA, category: CATEGORY, prompt: "ombre marcate realistiche, dettagli conservati, nessuna crepa" },

{ id: "hyper-col-balance-071", title: "Prodotto bianco corretto", summary: "Niente grigio.", area: AREA, category: CATEGORY, prompt: "prodotto bianco con dettaglio, bianco reale, senza grigio sporco" },
{ id: "hyper-col-balance-072", title: "Prodotto nero con dettaglio", summary: "Non bagnato.", area: AREA, category: CATEGORY, prompt: "prodotto nero con dettaglio, riflessi sottili, imballati" },
{ id: "hyper-col-balance-073", title: "Colore del marchio fedele", summary: "Elevazione.", area: AREA, category: CATEGORY, prompt: "vero colore per marcare riferimento, nessuna deviazione tono" },
{ id: "hyper-col-balance-074", title: "Fondo netto", summary: "Grigio morbido.", area: AREA, category: CATEGORY, prompt: "sfondo neutro (grigio morbido), soggetto con colore reale" },
{ id: "hyper-col-balance-075", title: "Sfondo caldo neutro", summary: "Beige.", area: AREA, category: CATEGORY, prompt: "sfondo caldo neutro (beige / crema), pelle naturale" },
{ id: "hyper-col-balance-076", title: "Sfondo freddo neutro", summary: "Blu grigio.", area: AREA, category: CATEGORY, prompt: "sfondo freddo neutro (blu / grigio), bianco pulito" },
{ id: "hyper-col-balance-077", title: "Accento rosso reale", summary: "Non neon.", area: AREA, category: CATEGORY, prompt: "accento rosso realistico, nessuna saturazione neon, dettaglio conservato" },
{ id: "hyper-col-balance-078", title: "Accento verde reale", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "accento verde realistico, nessuna variazione tonale radioattiva" },
{ id: "hyper-col-balance-079", title: "Accento blu reale", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "un accento blu realistico, senza cyan eccessivo" },
{ id: "hyper-col-balance-080", title: "Accento d'oro reale", summary: "Metallo.", area: AREA, category: CATEGORY, prompt: "accento dorato realistico, riflessi corretti, nessun giallo piatto" },

{ id: "hyper-col-balance-081", title: "Colore uniforme NO", summary: "Varia.", area: AREA, category: CATEGORY, prompt: "variazione di colore naturale, evitare uniformità artificiale" },
{ id: "hyper-col-balance-082", title: "Evitare 'porcelain' pelle", summary: "Texture.", area: AREA, category: CATEGORY, prompt: "evitare la pelle di porcellana, mantenere la variazione e la texture reale" },
{ id: "hyper-col-balance-083", title: "Evitare la pelle 'plastica'", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "evitare la pelle di plastica, speculare naturale, micromateriale" },
{ id: "hyper-col-balance-084", title: "Evitare il cielo falso", summary: "Vero.", area: AREA, category: CATEGORY, prompt: "evitare falsi cieli, mantenere gradiente e colore realistico" },
{ id: "hyper-col-balance-085", title: "Evitare ombre verdi", summary: "Pulito.", area: AREA, category: CATEGORY, prompt: "evitare ombre verdi, neutralizzare dominante" },
{ id: "hyper-col-balance-086", title: "Evitare i punti salienti cian", summary: "Controllo.", area: AREA, category: CATEGORY, prompt: "evitare alte luci cian, bianco naturale" },
{ id: "hyper-col-balance-087", title: "Evitare la posterizzazione", summary: "Morbido.", area: AREA, category: CATEGORY, prompt: "transizioni tonali morbide, senza posterizzazione" },
{ id: "hyper-col-balance-088", title: "Evitare l'eccesso di cibo", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "evitare di mangiare troppo, toni realistici, appetitosi credibili" },
{ id: "hyper-col-balance-089", title: "Evitare l'arancia in pelle", summary: "Pelle.", area: AREA, category: CATEGORY, prompt: "evitare la pelle arancione, sottotoni bilanciati" },
{ id: "hyper-col-balance-090", title: "Evitare la pelle magenta", summary: "Pelle.", area: AREA, category: CATEGORY, prompt: "evitare la pelle dominante magenta, mantenere la naturalità" },

{ id: "hyper-col-balance-091", title: "Bilanciamento della luce principale", summary: "Coerente.", area: AREA, category: CATEGORY, prompt: "equilibrio bianco secondo luce principale, consistenza globale" },
{ id: "hyper-col-balance-092", title: "Colore con riferimento grigio", summary: "Neutro.", area: AREA, category: CATEGORY, prompt: "neutralità grigio, bianco e grigio coerente" },
{ id: "hyper-col-balance-093", title: "Separazione della pelle", summary: "Pelle separata.", area: AREA, category: CATEGORY, prompt: "separazione della pelle tonale vs sfondo, naturale, senza tagli" },
{ id: "hyper-col-balance-094", title: "Colore ombra reale", summary: "Ambiente.", area: AREA, category: CATEGORY, prompt: "colore ombra coerente con l'ambiente, non puro nero" },
{ id: "hyper-col-balance-095", title: "Colore dei riflessi reali", summary: "Ambiente.", area: AREA, category: CATEGORY, prompt: "riflessi prendono colore dall'ambiente, fisica coerente" },
{ id: "hyper-col-balance-096", title: "Dominanti minimi", summary: "Pro.", area: AREA, category: CATEGORY, prompt: "dominio minimo e controllato, realismo" },
{ id: "hyper-col-balance-097", title: "Senso di film naturale", summary: "Film.", area: AREA, category: CATEGORY, prompt: "lieve sensazione di film, toni naturali, senza filtri aggressivi" },
{ id: "hyper-col-balance-098", title: "Colore pulito + dettaglio", summary: "Equilibrio.", area: AREA, category: CATEGORY, prompt: "colore pulito in dettaglio, senza eccessiva denoise" },
{ id: "hyper-col-balance-099", title: "Texture con colore reale", summary: "Materiale credibile.", area: AREA, category: CATEGORY, prompt: "texture con colore realistico, senza coloranti artificiali" },
{ id: "hyper-col-balance-100", title: "Risultati fotografici", summary: "Guarda.", area: AREA, category: CATEGORY, prompt: "realistico risultato fotografico, nessuna illustrazione stile, colore naturale" }];