// src/lib/prompts/hyperrealism-text/composicion.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Composizione";
const CATEGORY = "Encadre";

export const hyperrealismTextPromptsComposicion = [
{ id: "hyper-comp-encadre-001", title: "Regola di terze parti", summary: "Classico bilanciato.", area: AREA, category: CATEGORY, prompt: "composizione con regola di terze parti, equilibrio naturale" },
{ id: "hyper-comp-encadre-002", title: "Centro editoriale", summary: "Minimo pulito.", area: AREA, category: CATEGORY, prompt: "soggetto focalizzato, struttura editoriale pulita, simmetria sottile" },
{ id: "hyper-comp-encadre-003", title: "Simmetria perfetta", summary: "Ordine visivo.", area: AREA, category: CATEGORY, prompt: "simmetria perfetta, linee rette, composizione stabile" },
{ id: "hyper-comp-encadre-004", title: "Asimmetria controllata", summary: "Più dinamica.", area: AREA, category: CATEGORY, prompt: "asimmetria controllata, punto focale chiaro, equilibrio visivo" },
{ id: "hyper-comp-encadre-005", title: "Linee guida", summary: "Guida lo sguardo.", area: AREA, category: CATEGORY, prompt: "linee guida naturali (linee leader) al soggetto" },
{ id: "hyper-comp-encadre-006", title: "Triangolo visivo", summary: "Struttura pro.", area: AREA, category: CATEGORY, prompt: "composizione triangolo visivo, lettura chiara" },
{ id: "hyper-comp-encadre-007", title: "Capo 3 aerei", summary: "Profondità reale.", area: AREA, category: CATEGORY, prompt: "terra / centro / strati di sfondo, profondità naturale" },
{ id: "hyper-comp-encadre-008", title: "Quadro comunitario", summary: "Telaio interno.", area: AREA, category: CATEGORY, prompt: "cornice naturale (porta / finestra / rami) in primo piano" },
{ id: "hyper-comp-encadre-009", title: "Spazio negativo", summary: "Respira.", area: AREA, category: CATEGORY, prompt: "uso di spazio negativo, soggetto evidenziato, minimo" },
{ id: "hyper-comp-encadre-010", title: "Composizione diagonale", summary: "Azione.", area: AREA, category: CATEGORY, prompt: "sottile composizione diagonale, dinamismo inesagerato" },

{ id: "hyper-comp-encadre-011", title: "Livello degli occhi", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "angolo di livello dell'occhio (altezza dell'occhio), prospettiva umana" },
{ id: "hyper-comp-encadre-012", title: "Contributo delicato", summary: "Presenza.", area: AREA, category: CATEGORY, prompt: "peso leggero, proporzioni realistiche, nessuna deformazione" },
{ id: "hyper-comp-encadre-013", title: "Piede delicato", summary: "Controllo.", area: AREA, category: CATEGORY, prompt: "geometria leggera tritata, stabile e realistica" },
{ id: "hyper-comp-encadre-014", title: "Dettaglio piano", summary: "La texture e' al comando.", area: AREA, category: CATEGORY, prompt: "dettaglio piatto, concentrarsi sulla texture, telaio stretto" },
{ id: "hyper-comp-encadre-015", title: "Primo piano", summary: "Intimazia.", area: AREA, category: CATEGORY, prompt: "close-up, faccia o oggetto occupa la maggior parte del telaio" },
{ id: "hyper-comp-encadre-016", title: "Livello medio", summary: "Versatile.", area: AREA, category: CATEGORY, prompt: "piano medio, linguaggio del corpo visibile, composizione stabile" },
{ id: "hyper-comp-encadre-017", title: "Aereo americano", summary: "Cinema.", area: AREA, category: CATEGORY, prompt: "piano americano, estetica cinematografica, lettura chiara" },
{ id: "hyper-comp-encadre-018", title: "Livello generale", summary: "Contesto.", area: AREA, category: CATEGORY, prompt: "piano generale, piccolo soggetto, storia del conto ambientale" },
{ id: "hyper-comp-encadre-019", title: "3 / 4 classico", summary: "Profondità.", area: AREA, category: CATEGORY, prompt: "angolo 3 / 4, profondità naturale, prospettiva stabile" },
{ id: "hyper-comp-encadre-020", title: "Profilo", summary: "Pulito.", area: AREA, category: CATEGORY, prompt: "profilo marcato, linee pulite, sfondo semplice" },

{ id: "hyper-comp-encadre-021", title: "Dritto orizzontale", summary: "Evita di essere storto.", area: AREA, category: CATEGORY, prompt: "orizzonte perfettamente rettilineo, architettura stabile" },
{ id: "hyper-comp-encadre-022", title: "Architettura 1 punto", summary: "Una prospettiva chiara.", area: AREA, category: CATEGORY, prompt: "1 punto di vista, linee convergenti controllate" },
{ id: "hyper-comp-encadre-023", title: "Architettura 2 punti", summary: "Una vera città.", area: AREA, category: CATEGORY, prompt: "2 punti di vista, corretto verticale" },
{ id: "hyper-comp-encadre-024", title: "Legumi diritti", summary: "Niente caduta.", area: AREA, category: CATEGORY, prompt: "dritto verticale, senza apparente distorsione delle lenti" },
{ id: "hyper-comp-encadre-025", title: "Linee pulite", summary: "Ordine.", area: AREA, category: CATEGORY, prompt: "linee pulite, geometria costante, nessun caos visivo" },
{ id: "hyper-comp-encadre-026", title: "Focus sul tema", summary: "Priorita'.", area: AREA, category: CATEGORY, prompt: "unico punto focale, nulla compete con il soggetto" },
{ id: "hyper-comp-encadre-027", title: "Due punti focali", summary: "Rapporto.", area: AREA, category: CATEGORY, prompt: "due punti focali chiari, marcata gerarchia visiva" },
{ id: "hyper-comp-encadre-028", title: "Tasso visivo", summary: "Modelli reali.", area: AREA, category: CATEGORY, prompt: "ritmo visivo con ripetizione sottile, senza motivo artificiale" },
{ id: "hyper-comp-encadre-029", title: "Profondità in scala", summary: "Dimensioni reali.", area: AREA, category: CATEGORY, prompt: "profondità per scala (grandi, piccoli elementi vicini)" },
{ id: "hyper-comp-encadre-030", title: "Layering con primo piano", summary: "Immersione.", area: AREA, category: CATEGORY, prompt: "elemento di primo piano leggermente sfocato, immersione effettiva" },

{ id: "hyper-comp-encadre-031", title: "Telaio stretto", summary: "Impatto.", area: AREA, category: CATEGORY, prompt: "telaio stretto, nessuna aria extra, impatto visivo" },
{ id: "hyper-comp-encadre-032", title: "Incontro con l'aria", summary: "Elegante.", area: AREA, category: CATEGORY, prompt: "telaio con aria intorno, sensazione premium" },
{ id: "hyper-comp-encadre-033", title: "Correzione della testa", summary: "Proporzione.", area: AREA, category: CATEGORY, prompt: "corretto headroom (spazio superiore naturale), nessun taglio raro" },
{ id: "hyper-comp-encadre-034", title: "Nessun taglio scomodo", summary: "Corpo buono.", area: AREA, category: CATEGORY, prompt: "evitare le giunture di taglio (candele, polsi), taglio pulito" },
{ id: "hyper-comp-encadre-035", title: "Piano terra", summary: "Texture.", area: AREA, category: CATEGORY, prompt: "macchina fotografica del pavimento, visibile, realistica texture del pavimento" },
{ id: "hyper-comp-encadre-036", title: "Tabella", summary: "Prodotto.", area: AREA, category: CATEGORY, prompt: "fotocamera da tavolo, prodotto principale, non deformato" },
{ id: "hyper-comp-encadre-037", title: "Aerei da spalla", summary: "Storia.", area: AREA, category: CATEGORY, prompt: "angolo sopra la spalla, narrazione realistica" },
{ id: "hyper-comp-encadre-038", title: "POV aereo", summary: "Immergente.", area: AREA, category: CATEGORY, prompt: "vista POV, mani / oggetto in primo piano, realistico" },
{ id: "hyper-comp-encadre-039", title: "Piano a specchio", summary: "Riflessione credibile.", area: AREA, category: CATEGORY, prompt: "uso di specchio con riflessione coerente, senza duplicazione rara" },
{ id: "hyper-comp-encadre-040", title: "Aerei con riflesso", summary: "Acqua / vetro.", area: AREA, category: CATEGORY, prompt: "riflessi coerenti (vetro / acqua), corretta prospettiva fisica" },

{ id: "hyper-comp-encadre-041", title: "Ampia cinematica", summary: "Guarda il film.", area: AREA, category: CATEGORY, prompt: "ampia cornice di film, composizione calma" },
{ id: "hyper-comp-encadre-042", title: "Chiusura cinematica", summary: "Dramma morbido.", area: AREA, category: CATEGORY, prompt: "film di primo piano, emozione credibile, frame controllato" },
{ id: "hyper-comp-encadre-043", title: "Centro massaggi", summary: "Peso visivo.", area: AREA, category: CATEGORY, prompt: "equilibrata centro di massa visiva, sensazione stabile" },
{ id: "hyper-comp-encadre-044", title: "Pressione sui bordi", summary: "Attenta.", area: AREA, category: CATEGORY, prompt: "evitare materiali (oggetti bordi toccanti), separazione chiara" },
{ id: "hyper-comp-encadre-045", title: "Separazione sostanziale", summary: "Argomento in primo piano.", area: AREA, category: CATEGORY, prompt: "sottofondo per contrasto e profondità, naturale" },
{ id: "hyper-comp-encadre-046", title: "Priorità pulita", summary: "Niente rumore.", area: AREA, category: CATEGORY, prompt: "fondo pulito e coerente, senza elementi distratti" },
{ id: "hyper-comp-encadre-047", title: "Fondo di Contesto", summary: "Storia.", area: AREA, category: CATEGORY, prompt: "contesto realistico sfondo che rafforza la storia" },
{ id: "hyper-comp-encadre-048", title: "Elementi verticali", summary: "Dynamism.", area: AREA, category: CATEGORY, prompt: "elementi diagonali sottili, movimento inesagerato" },
{ id: "hyper-comp-encadre-049", title: "Silhouette trasparente", summary: "Lettura.", area: AREA, category: CATEGORY, prompt: "silhouette del soggetto chiaro e separato dallo sfondo" },
{ id: "hyper-comp-encadre-050", title: "Contrasto scala", summary: "Un impatto reale.", area: AREA, category: CATEGORY, prompt: "contrasto di scala (grande oggetto vs piccolo), realistico" },

{ id: "hyper-comp-encadre-051", title: "S-composizione", summary: "Flusso organico.", area: AREA, category: CATEGORY, prompt: "s composizione curva, flusso visivo organico" },
{ id: "hyper-comp-encadre-052", title: "C-composizione", summary: "Aspetta.", area: AREA, category: CATEGORY, prompt: "forma C in elementi, avvolgere delicatamente il soggetto" },
{ id: "hyper-comp-encadre-053", title: "Rapporto d'oro (sottotle)", summary: "Pro.", area: AREA, category: CATEGORY, prompt: "uso sottile di una proporzione di aura, gerarchia chiara" },
{ id: "hyper-comp-encadre-054", title: "Centro visivo basso", summary: "Peso a terra.", area: AREA, category: CATEGORY, prompt: "peso visivo leggermente inferiore, stabilità" },
{ id: "hyper-comp-encadre-055", title: "Alto centro visivo", summary: "Luce.", area: AREA, category: CATEGORY, prompt: "peso visivo leggermente sopra, sensazione di luce" },
{ id: "hyper-comp-encadre-056", title: "Dominante e accento", summary: "2 colori.", area: AREA, category: CATEGORY, prompt: "dominante + accento (colore / forma), semplice gerarchia" },
{ id: "hyper-comp-encadre-057", title: "Serie oggetti", summary: "Una vera ripetizione.", area: AREA, category: CATEGORY, prompt: "ripetizione oggettistica, variazione naturale minima" },
{ id: "hyper-comp-encadre-058", title: "Texture principale", summary: "Si sente Macro.", area: AREA, category: CATEGORY, prompt: "texture principale, cornice per microdetail" },
{ id: "hyper-comp-encadre-059", title: "Storia in primo piano", summary: "Props.", area: AREA, category: CATEGORY, prompt: "oggetti di primo piano che raccontano storia, realistico" },
{ id: "hyper-comp-encadre-060", title: "Storia in profondità", summary: "Contesto.", area: AREA, category: CATEGORY, prompt: "dettaglio approfondito che fornisce contesto, non distrae" },

{ id: "hyper-comp-encadre-061", title: "Triangolo leggero", summary: "Perception pro.", area: AREA, category: CATEGORY, prompt: "composizione che enfatizza la luce / triangolo ombra, naturale" },
{ id: "hyper-comp-encadre-062", title: "Luce come guida", summary: "Tour.", area: AREA, category: CATEGORY, prompt: "zone leggere guidano lo sguardo al soggetto" },
{ id: "hyper-comp-encadre-063", title: "Ombre come una cornice", summary: "Set.", area: AREA, category: CATEGORY, prompt: "ombre sottili inquadrano il soggetto senza coprirlo" },
{ id: "hyper-comp-encadre-064", title: "Contrasto focus", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "punto focale a contrasto morbido, senza HDR" },
{ id: "hyper-comp-encadre-065", title: "Focus by color", summary: "Atento.", area: AREA, category: CATEGORY, prompt: "punto focale di un accento di colore realistico" },
{ id: "hyper-comp-encadre-066", title: "Focus sulla nitidezza", summary: "Gerarchia.", area: AREA, category: CATEGORY, prompt: "gerarchia per nitidezza: soggetto più affilato, sfondo morbido" },
{ id: "hyper-comp-encadre-067", title: "Bokeh come separazione", summary: "DOF.", area: AREA, category: CATEGORY, prompt: "bokeh graduale e realistico per separare i piani" },
{ id: "hyper-comp-encadre-068", title: "Fall in focus", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "progressivo, approccio non artificiale caduta" },
{ id: "hyper-comp-encadre-069", title: "Centro fuori dal centro", summary: "Dinamica.", area: AREA, category: CATEGORY, prompt: "soggetto esterno al centro, bilanciato da contrappeso visivo" },
{ id: "hyper-comp-encadre-070", title: "Minimalismo per", summary: "Pochi elementi.", area: AREA, category: CATEGORY, prompt: "minimalismo: pochi elementi, composizione pulita e realistica" },

{ id: "hyper-comp-encadre-071", title: "Top-down (ash)", summary: "Aereo cenitale reale.", area: AREA, category: CATEGORY, prompt: "piano perfettamente allineato (top-down)" },
{ id: "hyper-comp-encadre-072", title: "tabella da 45 °", summary: "Cibo / prodotto.", area: AREA, category: CATEGORY, prompt: "45 ° angolo su tavola, aspetto editoriale, realistico" },
{ id: "hyper-comp-encadre-073", title: "Piano laterale", summary: "Oggetto del profilo.", area: AREA, category: CATEGORY, prompt: "piano laterale, profilo pulito, linee rette" },
{ id: "hyper-comp-encadre-074", title: "Macro parziale", summary: "Sezione.", area: AREA, category: CATEGORY, prompt: "macro parziale, cornice di una sezione con texture" },
{ id: "hyper-comp-encadre-075", title: "Regola orizzontale", summary: "1 / 3 su.", area: AREA, category: CATEGORY, prompt: "orizzonte in alto o inferiore terzo, paesaggio realistico" },
{ id: "hyper-comp-encadre-076", title: "Fondo non focalizzato", summary: "Ritratto.", area: AREA, category: CATEGORY, prompt: "sfondo sfocato con bokeh realistico, nessun taglio raro" },
{ id: "hyper-comp-encadre-077", title: "Forte primo piano", summary: "Capes.", area: AREA, category: CATEGORY, prompt: "primo piano forte, medio piano narrativo, fondo morbido" },
{ id: "hyper-comp-encadre-078", title: "Separazione della luce", summary: "Concircolo.", area: AREA, category: CATEGORY, prompt: "morbido cerchio luce separazione (se applicabile), profilo naturale" },
{ id: "hyper-comp-encadre-079", title: "Set con fiocco", summary: "Architettura.", area: AREA, category: CATEGORY, prompt: "archi / strutture cornice soggetto, corretta prospettiva" },
{ id: "hyper-comp-encadre-080", title: "Modello rotto", summary: "Un dettaglio diverso.", area: AREA, category: CATEGORY, prompt: "schema ripetuto con un elemento diverso come messa a fuoco" },

{ id: "hyper-comp-encadre-081", title: "Chiarezza della storia", summary: "1 idea.", area: AREA, category: CATEGORY, prompt: "un'unica idea visiva dominante, storia chiara" },
{ id: "hyper-comp-encadre-082", title: "Gerarchia 3 livelli", summary: "Ordine.", area: AREA, category: CATEGORY, prompt: "gerarchia visiva: primario / secondario / terziario, chiaro" },
{ id: "hyper-comp-encadre-083", title: "No", summary: "Evitare il disturbo.", area: AREA, category: CATEGORY, prompt: "senza ingombro, elementi minimi e coerenti" },
{ id: "hyper-comp-encadre-084", title: "Centro di interesse pulito", summary: "Niente distrae.", area: AREA, category: CATEGORY, prompt: "centro di interesse pulito, senza oggetti concorrenti" },
{ id: "hyper-comp-encadre-085", title: "Scala umana", summary: "Vero.", area: AREA, category: CATEGORY, prompt: "corretta scala umana in oggetti / ambiente" },
{ id: "hyper-comp-encadre-086", title: "Proporzioni anatomiche", summary: "Corpo reale.", area: AREA, category: CATEGORY, prompt: "corrette proporzioni anatomiche, senza deformazioni" },
{ id: "hyper-comp-encadre-087", title: "Posa naturale", summary: "Nessuna rigidità.", area: AREA, category: CATEGORY, prompt: "posa naturale (senza rigidità), posizione credibile" },
{ id: "hyper-comp-encadre-088", title: "I gesti realistici", summary: "Mani plausibili.", area: AREA, category: CATEGORY, prompt: "gesti realistici su mani / viso, senza dita extra" },
{ id: "hyper-comp-encadre-089", title: "Interazione con oggetto", summary: "Una vera storia.", area: AREA, category: CATEGORY, prompt: "interazione del soggetto - oggetto credibile, contatto naturale" },
{ id: "hyper-comp-encadre-090", title: "Azione congelata", summary: "Aspetta.", area: AREA, category: CATEGORY, prompt: "cattura di un momento (azione) con composizione chiara" },

{ id: "hyper-comp-encadre-091", title: "Obiettivo", summary: "Ritratto superiore.", area: AREA, category: CATEGORY, prompt: "attenzione agli occhi, composizione incentrata" },
{ id: "hyper-comp-encadre-092", title: "Guarda nello spazio", summary: "Indirizzo.", area: AREA, category: CATEGORY, prompt: "soggetto guardando in spazio negativo, direzione chiara" },
{ id: "hyper-comp-encadre-093", title: "Vista panoramica", summary: "Collegamento.", area: AREA, category: CATEGORY, prompt: "vista telecamera, collegamento diretto, cornice pulita" },
{ id: "hyper-comp-encadre-094", title: "Uscita 3 / 4", summary: "E-commerce pro.", area: AREA, category: CATEGORY, prompt: "3 / 4 prodotto angolo, ombra realistica, sfondo pulito" },
{ id: "hyper-comp-encadre-095", title: "Prodotto concentrato", summary: "Pacchetti.", area: AREA, category: CATEGORY, prompt: "prodotto concentrato, simmetria leggera, composizione e-commerce" },
{ id: "hyper-comp-encadre-096", title: "Cibo 45 °", summary: "Cibo standard.", area: AREA, category: CATEGORY, prompt: "45 ° composizione alimentare, oggetti minimi, guardare editoriale" },
{ id: "hyper-comp-encadre-097", title: "Cibo", summary: "Vista superiore.", area: AREA, category: CATEGORY, prompt: "cibo, allineamento perfetto, ordine pulito" },
{ id: "hyper-comp-encadre-098", title: "Urbano con profondità", summary: "Strada reale.", area: AREA, category: CATEGORY, prompt: "strada con profondità marcata, soggetto in terza, linea guida" },
{ id: "hyper-comp-encadre-099", title: "Interno con linee", summary: "Architettura.", area: AREA, category: CATEGORY, prompt: "interno con linee rette, composizione stabile, verticale corretta" },
{ id: "hyper-comp-encadre-100", title: "Studio minimo", summary: "Premium.", area: AREA, category: CATEGORY, prompt: "studio minimo, sfondo pulito, composizione premium realistica" }];