// src/lib/prompts/hyperrealism-text/materiales.js
// Área y categoría ÚNICAS para TODO este archivo:
const AREA = "Materiali";
const CATEGORY = "Textures";

export const hyperrealismTextPromptsMateriales = [
{ id: "hyper-mat-texturas-001", title: "Vera pelle umana", summary: "Pores e microimperfezioni.", area: AREA, category: CATEGORY, prompt: "texture vera pelle, pori visibili, microimperfezioni naturali" },
{ id: "hyper-mat-texturas-002", title: "Capelli fini", summary: "Peach fuzz realistico.", area: AREA, category: CATEGORY, prompt: "capelli sottili (peach fuzz), naturali, senza sovrastamento" },
{ id: "hyper-mat-texturas-003", title: "Microrughe", summary: "Eta' credibile.", area: AREA, category: CATEGORY, prompt: "microrughe realistiche, texture naturale, senza filtro di bellezza" },
{ id: "hyper-mat-texturas-004", title: "Pecas e macchie sottili", summary: "Una vera varietà.", area: AREA, category: CATEGORY, prompt: "lentiggini / macchie sottili, variazione naturale della pelle" },
{ id: "hyper-mat-texturas-005", title: "Labbra reali", summary: "Texture e umidità.", area: AREA, category: CATEGORY, prompt: "labbra con texture reale, umidità sottile, senza plastica" },
{ id: "hyper-mat-texturas-006", title: "Occhi realistici", summary: "Umidità e riflessi.", area: AREA, category: CATEGORY, prompt: "occhi realistici, riflessione costante, umidità sottile, nessun look da polso" },
{ id: "hyper-mat-texturas-007", title: "Pesci naturali", summary: "Nessun fan falso.", area: AREA, category: CATEGORY, prompt: "schede naturali, densità reale, nessun modello ripetuto" },
{ id: "hyper-mat-texturas-008", title: "Capelli fini", summary: "Ebron individuale.", area: AREA, category: CATEGORY, prompt: "capelli con ciocche definite, variazione naturale, senza blocchi" },
{ id: "hyper-mat-texturas-009", title: "Barba reale", summary: "Follicoli e ombre.", area: AREA, category: CATEGORY, prompt: "barba realistica, follicoli visibili, ombra naturale, senza texture verniciata" },
{ id: "hyper-mat-texturas-010", title: "Sudore sottile", summary: "Un vero splendore.", area: AREA, category: CATEGORY, prompt: "sudore sottile, bagliore realistico, nessun effetto bagnato eccessivo" },

{ id: "hyper-mat-texturas-011", title: "Cotone", summary: "Tessuti visibili.", area: AREA, category: CATEGORY, prompt: "tessuto di cotone, tessuto visibile, rughe naturali" },
{ id: "hyper-mat-texturas-012", title: "Lino", summary: "Fibra irregolare.", area: AREA, category: CATEGORY, prompt: "lino realistico, fibra irregolare, rughe organiche" },
{ id: "hyper-mat-texturas-013", title: "Denim", summary: "Traccia e indossa.", area: AREA, category: CATEGORY, prompt: "denim con tessuto visibile, usura sottile, cuciture reali" },
{ id: "hyper-mat-texturas-014", title: "Maglia in pelle", summary: "Pores e grano.", area: AREA, category: CATEGORY, prompt: "pelle opaca, grano visibile, micrograffi sottili" },
{ id: "hyper-mat-texturas-015", title: "Pelle luminosa", summary: "Una riflessione controllata.", area: AREA, category: CATEGORY, prompt: "pelle leggermente luminosa, riflessi controllati, senza plastica" },
{ id: "hyper-mat-texturas-016", title: "Gamuza", summary: "Capelli di pinna.", area: AREA, category: CATEGORY, prompt: "sluice con macchie fini, naturali ombreggiate, senza macchie rare" },
{ id: "hyper-mat-texturas-017", title: "Seta", summary: "Morbido splendore.", area: AREA, category: CATEGORY, prompt: "seta realistica, luminosità anisotropica morbida, pieghe credibili" },
{ id: "hyper-mat-texturas-018", title: "Raso", summary: "Un riflesso marcato.", area: AREA, category: CATEGORY, prompt: "satinato, marcato ma reale, senza sovraesposizione" },
{ id: "hyper-mat-texturas-019", title: "Lana", summary: "Fibra di gomma.", area: AREA, category: CATEGORY, prompt: "lana in fibra visibile, volume effettivo, senza modelli ripetuti" },
{ id: "hyper-mat-texturas-020", title: "Tessuto", summary: "Guarda visibile.", area: AREA, category: CATEGORY, prompt: "tessuto lavorato a maglia, cappi visibili, texture realistica" },

{ id: "hyper-mat-texturas-021", title: "Metallo spazzolato", summary: "Belle strisce.", area: AREA, category: CATEGORY, prompt: "metallo spazzolato, linee sottili, riflessione realistica" },
{ id: "hyper-mat-texturas-022", title: "Acciaio inossidabile", summary: "Riflessioni reali.", area: AREA, category: CATEGORY, prompt: "acciaio inossidabile, riflessi morbidi, micrograffi discreti" },
{ id: "hyper-mat-texturas-023", title: "Alluminio", summary: "Mate light.", area: AREA, category: CATEGORY, prompt: "alluminio opaco, riflesso tenue, bordi taglienti" },
{ id: "hyper-mat-texturas-024", title: "Chrome", summary: "Specchio.", area: AREA, category: CATEGORY, prompt: "cromo, riflessione a specchio coerente, senza distorsione impossibile" },
{ id: "hyper-mat-texturas-025", title: "Ottone", summary: "Tono caldo.", area: AREA, category: CATEGORY, prompt: "ottone realistico, tono caldo, patina sottile" },
{ id: "hyper-mat-texturas-026", title: "Rame", summary: "Leggero.", area: AREA, category: CATEGORY, prompt: "rame realistico, patina leggera, macchie naturali" },
{ id: "hyper-mat-texturas-027", title: "Ferro forgiato", summary: "Una vera rugosità.", area: AREA, category: CATEGORY, prompt: "ferro battuto, vera rugosità, usura naturale" },
{ id: "hyper-mat-texturas-028", title: "Metallo verniciato", summary: "Despostillato.", area: AREA, category: CATEGORY, prompt: "metallo verniciato, sottile vernice despostillata, bordo passato" },
{ id: "hyper-mat-texturas-029", title: "Rust metal", summary: "Ossido credibile.", area: AREA, category: CATEGORY, prompt: "ossido realistico, granularità naturale, senza ripetizione" },
{ id: "hyper-mat-texturas-030", title: "Royal bullfighting", summary: "Dettagli meccanici.", area: AREA, category: CATEGORY, prompt: "viti realistiche / rivetti, micrograffi, sporco sottile" },

{ id: "hyper-mat-texturas-031", title: "Vetro pulito", summary: "Una vera trasparenza.", area: AREA, category: CATEGORY, prompt: "vetro pulito, rifrazione costante, riflessi morbidi" },
{ id: "hyper-mat-texturas-032", title: "Vetro ermetico", summary: "Morbida diffusione.", area: AREA, category: CATEGORY, prompt: "vetro emerylated, diffusione reale, nessun rumore straniero" },
{ id: "hyper-mat-texturas-033", title: "Vetro con polvere", summary: "Microimperfezione.", area: AREA, category: CATEGORY, prompt: "vetro con polvere sottile, stampe leggere e realistiche" },
{ id: "hyper-mat-texturas-034", title: "Plastica opaco", summary: "Nessun look economico.", area: AREA, category: CATEGORY, prompt: "plastica opaca realistica, microtexture, nessun aspetto giocattolo" },
{ id: "hyper-mat-texturas-035", title: "Plastica luminosa", summary: "Una riflessione controllata.", area: AREA, category: CATEGORY, prompt: "plastica luminosa, riflessi controllati, non bruciato" },
{ id: "hyper-mat-texturas-036", title: "Acrilico", summary: "Sgombrate.", area: AREA, category: CATEGORY, prompt: "acrilico trasparente, bordi taglienti, rifrazione corretta" },
{ id: "hyper-mat-texturas-037", title: "Resina", summary: "Semitraslucido.", area: AREA, category: CATEGORY, prompt: "resina semitraslucida, bolle minime realistiche" },
{ id: "hyper-mat-texturas-038", title: "Ceramica opaca", summary: "Granelli fini.", area: AREA, category: CATEGORY, prompt: "ceramica opaca, granuli fini, imperfezioni sottili" },
{ id: "hyper-mat-texturas-039", title: "Ceramica denominata", summary: "Un vero splendore.", area: AREA, category: CATEGORY, prompt: "ceramica smaltata, luminosità realistica, microdefetti" },
{ id: "hyper-mat-texturas-040", title: "Porcellana", summary: "Niente eccesso.", area: AREA, category: CATEGORY, prompt: "porcellana realistica, nessun look in plastica, morbido riflesso" },

{ id: "hyper-mat-texturas-041", title: "Legno di quercia", summary: "Via libera.", area: AREA, category: CATEGORY, prompt: "legno di quercia, visibile, poro naturale, senza ripetizione" },
{ id: "hyper-mat-texturas-042", title: "Legno nonale", summary: "Veta oscura.", area: AREA, category: CATEGORY, prompt: "legno di noce, vena ricca, lucentezza sottile, lieve usura" },
{ id: "hyper-mat-texturas-043", title: "Legno verniciato", summary: "Hai scaricato sui bordi.", area: AREA, category: CATEGORY, prompt: "legno verniciato, usura su bordi, strati visibili" },
{ id: "hyper-mat-texturas-044", title: "Barniz", summary: "Riflessione morbida.", area: AREA, category: CATEGORY, prompt: "vernice realistica, riflessione morbida, nessun effetto specchio falso" },
{ id: "hyper-mat-texturas-045", title: "Vecchio legno", summary: "Crepe sottili.", area: AREA, category: CATEGORY, prompt: "legno invecchiato, fessure sottili, tagli minimi" },
{ id: "hyper-mat-texturas-046", title: "Concrete", summary: "Pore e macchie.", area: AREA, category: CATEGORY, prompt: "calcestruzzo realistico, pori visibili, macchie sottili, fessure sottili" },
{ id: "hyper-mat-texturas-047", title: "Cemento lucido", summary: "Morbido con segni.", area: AREA, category: CATEGORY, prompt: "cemento lucido, micrograffi, riflesso tenue" },
{ id: "hyper-mat-texturas-048", title: "Mattone", summary: "Un vero mortaio.", area: AREA, category: CATEGORY, prompt: "mattone realistico, malta irregolare, usura naturale" },
{ id: "hyper-mat-texturas-049", title: "Yeso / parete", summary: "Bene.", area: AREA, category: CATEGORY, prompt: "parete in gesso, grana fine, imperfezioni sottili" },
{ id: "hyper-mat-texturas-050", title: "Asfalto", summary: "Granulato.", area: AREA, category: CATEGORY, prompt: "asfalto realistico, granulato visibile, polvere sottile" },

{ id: "hyper-mat-texturas-051", title: "Pietra di marmo", summary: "Torte vere.", area: AREA, category: CATEGORY, prompt: "marmo realistico, vene uniche, lucentezza morbida, senza motivo ripetuto" },
{ id: "hyper-mat-texturas-052", title: "Granito", summary: "Punti minerali.", area: AREA, category: CATEGORY, prompt: "granito realistico, punti minerali, microgloss naturale" },
{ id: "hyper-mat-texturas-053", title: "Pizarra", summary: "Capes.", area: AREA, category: CATEGORY, prompt: "ardesia, strati visibili, texture robusta reale" },
{ id: "hyper-mat-texturas-054", title: "Sabbia", summary: "Grani visibili.", area: AREA, category: CATEGORY, prompt: "sabbia realistica, venature visibili, stampe sottili" },
{ id: "hyper-mat-texturas-055", title: "Terra bagnata", summary: "La realtà.", area: AREA, category: CATEGORY, prompt: "terra bagnata, scanalature naturali, sottile luminosità" },
{ id: "hyper-mat-texturas-056", title: "Pascolo", summary: "Varie foglie.", area: AREA, category: CATEGORY, prompt: "erba realistica, foglie varie, senza ripetizione" },
{ id: "hyper-mat-texturas-057", title: "Foglie", summary: "Vendite visibili.", area: AREA, category: CATEGORY, prompt: "foglie con venature visibili, microimperfezioni naturali" },
{ id: "hyper-mat-texturas-058", title: "Barca", summary: "Rugosity.", area: AREA, category: CATEGORY, prompt: "albero corteccia, vera rugosità, muschio sottile" },
{ id: "hyper-mat-texturas-059", title: "Rock", summary: "Fissure.", area: AREA, category: CATEGORY, prompt: "roccia realistica, fessure sottili, polvere naturale" },
{ id: "hyper-mat-texturas-060", title: "Neve", summary: "Cristalli morbidi.", area: AREA, category: CATEGORY, prompt: "neve realistica, texture morbida, luminosità sottile, senza plastica" },

{ id: "hyper-mat-texturas-061", title: "Acqua pulita", summary: "Riflessione e rifrazione.", area: AREA, category: CATEGORY, prompt: "acqua pulita, riflessi coerenti, vera rifrazione" },
{ id: "hyper-mat-texturas-062", title: "Acqua con gocce", summary: "Perle vere.", area: AREA, category: CATEGORY, prompt: "gocce d'acqua, tensione superficiale realistica, perle naturali" },
{ id: "hyper-mat-texturas-063", title: "Conviazione", summary: "Vetro freddo.", area: AREA, category: CATEGORY, prompt: "condensazione realistica, piccole gocce, sottile sentiero" },
{ id: "hyper-mat-texturas-064", title: "Ghiaccio", summary: "Bolle.", area: AREA, category: CATEGORY, prompt: "ghiaccio realistico, fratture interne, sottili bolle" },
{ id: "hyper-mat-texturas-065", title: "Vapore sottile", summary: "Davvero caldo.", area: AREA, category: CATEGORY, prompt: "vapore sottile realistico, senza nebbia artificiale" },
{ id: "hyper-mat-texturas-066", title: "Fumo morbido", summary: "Una vera diffusione.", area: AREA, category: CATEGORY, prompt: "fumo morbido realistico, diffusione naturale, nessuna macchia" },
{ id: "hyper-mat-texturas-067", title: "Polvere sottile", summary: "La realtà.", area: AREA, category: CATEGORY, prompt: "polvere sottile su superfici, accumulo naturale" },
{ id: "hyper-mat-texturas-068", title: "Davvero sporco", summary: "Niente di esagerato.", area: AREA, category: CATEGORY, prompt: "sporcizia realistica mite, macchie naturali, nessuna esagerazione" },
{ id: "hyper-mat-texturas-069", title: "Belle Rayons", summary: "Uso reale.", area: AREA, category: CATEGORY, prompt: "micrograffi fine, usura per uso, realistico" },
{ id: "hyper-mat-texturas-070", title: "Landing", summary: "Indosso d'angolo.", area: AREA, category: CATEGORY, prompt: "usura sui bordi, vernice indossata sottile, realistico" },

{ id: "hyper-mat-texturas-071", title: "Matematica carta", summary: "Fibra visibile.", area: AREA, category: CATEGORY, prompt: "carta opaca, fibra visibile, grano naturale" },
{ id: "hyper-mat-texturas-072", title: "Carta brillante", summary: "Riflessione.", area: AREA, category: CATEGORY, prompt: "carta luminosa, riflesso controllato, non bruciato" },
{ id: "hyper-mat-texturas-073", title: "Cartone", summary: "Onda.", area: AREA, category: CATEGORY, prompt: "cartone realistico, texture ondulata, bordi fibrosi" },
{ id: "hyper-mat-texturas-074", title: "Notebook", summary: "Foglie vere.", area: AREA, category: CATEGORY, prompt: "pagine di notebook, texture carta, ombre morbide" },
{ id: "hyper-mat-texturas-075", title: "Inchiostro e corsa", summary: "Imperfezione.", area: AREA, category: CATEGORY, prompt: "inchiostro realistico, variazioni di luce, senza bordi perfetti" },
{ id: "hyper-mat-texturas-076", title: "Stampa reale", summary: "Niente bandi.", area: AREA, category: CATEGORY, prompt: "impressione realistica, trama sottile, senza banding" },
{ id: "hyper-mat-texturas-077", title: "Etichetta adesivo", summary: "Un vero successo.", area: AREA, category: CATEGORY, prompt: "etichetta adesivo, bordo minimo sollevato, texture reale" },
{ id: "hyper-mat-texturas-078", title: "Tessuto ricamato", summary: "Discussione.", area: AREA, category: CATEGORY, prompt: "ricamo realistico, fili visibili, rilievo sottile" },
{ id: "hyper-mat-texturas-079", title: "Sedili", summary: "Score.", area: AREA, category: CATEGORY, prompt: "cuciture realistiche, punti visibili, tensione naturale" },
{ id: "hyper-mat-texturas-080", title: "Pulsanti", summary: "Dettagli.", area: AREA, category: CATEGORY, prompt: "pulsanti realistici, luminosità sottile, micrograffi" },

{ id: "hyper-mat-texturas-081", title: "Gomma / gomma", summary: "Uccidi con i pori.", area: AREA, category: CATEGORY, prompt: "gomma realistica, poro fine, polvere sottile, senza plastica" },
{ id: "hyper-mat-texturas-082", title: "Spuma", summary: "Grandi pori.", area: AREA, category: CATEGORY, prompt: "schiuma realistica, pori visibili, ombre morbide" },
{ id: "hyper-mat-texturas-083", title: "Neoprene", summary: "Texture uniforme.", area: AREA, category: CATEGORY, prompt: "neoprene realistico, texture uniforme, bordi puliti" },
{ id: "hyper-mat-texturas-084", title: "Vernice raso", summary: "Semi-luce.", area: AREA, category: CATEGORY, prompt: "vernice satinata, media luminosità realistica, microtexture" },
{ id: "hyper-mat-texturas-085", title: "Chiodo reale", summary: "Piccolo splendore.", area: AREA, category: CATEGORY, prompt: "unghie realistiche, smalto con lucentezza sottile, cuticola naturale" },
{ id: "hyper-mat-texturas-086", title: "Trucco reale", summary: "Nessun filtro.", area: AREA, category: CATEGORY, prompt: "trucco realistico, texture visibile, nessun effetto airbrush" },
{ id: "hyper-mat-texturas-087", title: "Tessuto bagnato", summary: "E' buio.", area: AREA, category: CATEGORY, prompt: "tessuto umido realistico, oscuramento naturale, gocce sottili" },
{ id: "hyper-mat-texturas-088", title: "Abbigliamento naturale rugoso", summary: "Dei veri coperchi.", area: AREA, category: CATEGORY, prompt: "rughe di abbigliamento naturale, tensione realistica, nessun pattern" },
{ id: "hyper-mat-texturas-089", title: "Pelle con cicatrice mite", summary: "La realtà.", area: AREA, category: CATEGORY, prompt: "realistico cicatrice mite, consistenza costante, inesagerato" },
{ id: "hyper-mat-texturas-090", title: "Pelle con porosità", summary: "Naturale.", area: AREA, category: CATEGORY, prompt: "porosità naturale, variazione di tono, nessuna pelle di porcellana" },

{ id: "hyper-mat-texturas-091", title: "Cibo croccante", summary: "Texture.", area: AREA, category: CATEGORY, prompt: "texture croccante realistica, briciole sottili, dettaglio" },
{ id: "hyper-mat-texturas-092", title: "Cibo succoso", summary: "Wet.", area: AREA, category: CATEGORY, prompt: "realistico succoso, luce naturale, senza plastica" },
{ id: "hyper-mat-texturas-093", title: "Cioccolata", summary: "Splendi e fiorisci.", area: AREA, category: CATEGORY, prompt: "cioccolato realistico, fioritura sottile, riflesso morbido" },
{ id: "hyper-mat-texturas-094", title: "Pane", summary: "Miga.", area: AREA, category: CATEGORY, prompt: "pane realistico, miga visibile, taglio naturale" },
{ id: "hyper-mat-texturas-095", title: "Frutta", summary: "Cascara.", area: AREA, category: CATEGORY, prompt: "frutta realistica, buccia con pori, lucentezza naturale" },
{ id: "hyper-mat-texturas-096", title: "Carni bovine", summary: "Fibres.", area: AREA, category: CATEGORY, prompt: "carne realistica, fibre sottili, grasso naturale" },
{ id: "hyper-mat-texturas-097", title: "Formaggio", summary: "Pores.", area: AREA, category: CATEGORY, prompt: "formaggio realistico, pori e lucentezza, taglio naturale" },
{ id: "hyper-mat-texturas-098", title: "Salsa", summary: "Viscosità.", area: AREA, category: CATEGORY, prompt: "salsa realistica, viscosità coerente, riflessione morbida" },
{ id: "hyper-mat-texturas-099", title: "Nuovi imballaggi", summary: "Niente usura.", area: AREA, category: CATEGORY, prompt: "nuovo materiale, superficie pulita, vero micromateriale" },
{ id: "hyper-mat-texturas-100", title: "Pacchetto usato", summary: "Uso reale.", area: AREA, category: CATEGORY, prompt: "materiale usato, usura leggera, micrograffi realistici" }];